# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test NonEmptyDomain")

model.instance <- NonEmptyDomain$new()

test_that("nonEmptyDomain", {
  # tests for the property `nonEmptyDomain` (DomainArray)

  # uncomment below to test the property 
  #expect_equal(model.instance$`nonEmptyDomain`, "EXPECTED_RESULT")
})

test_that("isEmpty", {
  # tests for the property `isEmpty` (character)
  # Is non-empty domain really empty?

  # uncomment below to test the property 
  #expect_equal(model.instance$`isEmpty`, "EXPECTED_RESULT")
})

