# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test LastAccessedArray")

model.instance <- LastAccessedArray$new()

test_that("array_id", {
  # tests for the property `array_id` (character)
  # unique id of array

  # uncomment below to test the property 
  #expect_equal(model.instance$`array_id`, "EXPECTED_RESULT")
})

test_that("array_name", {
  # tests for the property `array_name` (character)
  # name of the array

  # uncomment below to test the property 
  #expect_equal(model.instance$`array_name`, "EXPECTED_RESULT")
})

test_that("namespace", {
  # tests for the property `namespace` (character)
  # namespace of a user or organization

  # uncomment below to test the property 
  #expect_equal(model.instance$`namespace`, "EXPECTED_RESULT")
})

test_that("accessed_time", {
  # tests for the property `accessed_time` (numeric)
  # timestamp (epoch milliseconds) array is last accessed

  # uncomment below to test the property 
  #expect_equal(model.instance$`accessed_time`, "EXPECTED_RESULT")
})

test_that("access_type", {
  # tests for the property `access_type` (ActivityEventType)

  # uncomment below to test the property 
  #expect_equal(model.instance$`access_type`, "EXPECTED_RESULT")
})

