# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ArrayTaskLog")

model.instance <- ArrayTaskLog$new()

test_that("array_task_id", {
  # tests for the property `array_task_id` (character)
  # ID of associated task

  # uncomment below to test the property 
  #expect_equal(model.instance$`array_task_id`, "EXPECTED_RESULT")
})

test_that("logs", {
  # tests for the property `logs` (character)
  # logs from array task

  # uncomment below to test the property 
  #expect_equal(model.instance$`logs`, "EXPECTED_RESULT")
})

