# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AttributeBufferHeader")

model.instance <- AttributeBufferHeader$new()

test_that("name", {
  # tests for the property `name` (character)
  # Attribute name

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("fixedLenBufferSizeInBytes", {
  # tests for the property `fixedLenBufferSizeInBytes` (integer)
  # Number of bytes in the fixed-length attribute data buffer (offsets for var-len attributes)

  # uncomment below to test the property 
  #expect_equal(model.instance$`fixedLenBufferSizeInBytes`, "EXPECTED_RESULT")
})

test_that("varLenBufferSizeInBytes", {
  # tests for the property `varLenBufferSizeInBytes` (integer)
  # Number of bytes in the var-length attribute data buffer

  # uncomment below to test the property 
  #expect_equal(model.instance$`varLenBufferSizeInBytes`, "EXPECTED_RESULT")
})

