# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TokenRequest")

model.instance <- TokenRequest$new()

test_that("expires", {
  # tests for the property `expires` (character)
  # Expiration date for token, if empty token defaults to 30 minutes

  # uncomment below to test the property 
  #expect_equal(model.instance$`expires`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # Optional name for token, if the name already exists for the user it will be auto incremented (i.e. myToken-1)

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("scope", {
  # tests for the property `scope` (character)
  # Optional scope to limit token, defaults to all permissions, current supported values are password_reset or *

  # uncomment below to test the property 
  #expect_equal(model.instance$`scope`, "EXPECTED_RESULT")
})

