# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InvitationApi")

api.instance <- InvitationApi$new()

test_that("AcceptInvitation", {
  # tests for AcceptInvitation
  # base path: http://localhost/v1
  # Accepts invitation
  # @param invitation character the id of invitation about to be accepted
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CancelJoinOrganization", {
  # tests for CancelJoinOrganization
  # base path: http://localhost/v1
  # Cancels join organization invitation
  # @param invitation character the id of invitation about to be cancelled
  # @param organization character name or uuid of organization
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CancelShareArrayByInvite", {
  # tests for CancelShareArrayByInvite
  # base path: http://localhost/v1
  # Cancels array sharing invitation
  # @param namespace character namespace array is in (an organization name or user's username)
  # @param invitation character the id of invitation about to be cancelled
  # @param array character name/uri of array that is url-encoded
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("FetchInvitations", {
  # tests for FetchInvitations
  # base path: http://localhost/v1
  # Fetch a list of invitations
  # @param organization character name or id of organization to filter (optional)
  # @param array character name/uri of array that is url-encoded to filter (optional)
  # @param start integer start time for tasks to filter by (optional)
  # @param end integer end time for tasks to filter by (optional)
  # @param page integer pagination offset (optional)
  # @param per.page integer pagination limit (optional)
  # @param type character invitation type, \"ARRAY_SHARE\", \"JOIN_ORGANIZATION\" (optional)
  # @param status character Filter to only return \"PENDING\", \"ACCEPTED\" (optional)
  # @param orderby character sort by which field valid values include timestamp, array_name, organization_name (optional)
  # @return [InvitationData]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("JoinOrganization", {
  # tests for JoinOrganization
  # base path: http://localhost/v1
  # Sends email to multiple recipients with joining information regarding an organization
  # @param organization character name or uuid of organization
  # @param email.invite InvitationOrganizationJoinEmail list of email recipients
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ShareArrayByInvite", {
  # tests for ShareArrayByInvite
  # base path: http://localhost/v1
  # Sends email to multiple recipients with sharing information regarding an array
  # @param namespace character namespace array is in (an organization name or user's username)
  # @param array character name/uri of array that is url-encoded
  # @param email.invite InvitationArrayShareEmail list of email recipients
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

