# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test FilterPipeline")

model.instance <- FilterPipeline$new()

test_that("filters", {
  # tests for the property `filters` (array[Filter])

  # uncomment below to test the property 
  #expect_equal(model.instance$`filters`, "EXPECTED_RESULT")
})

