# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SubarrayRanges")

model.instance <- SubarrayRanges$new()

test_that("type", {
  # tests for the property `type` (Datatype)

  # uncomment below to test the property 
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("hasDefaultRange", {
  # tests for the property `hasDefaultRange` (character)
  # True if the range is the default range

  # uncomment below to test the property 
  #expect_equal(model.instance$`hasDefaultRange`, "EXPECTED_RESULT")
})

test_that("buffer", {
  # tests for the property `buffer` (array[integer])
  # The bytes of the ranges

  # uncomment below to test the property 
  #expect_equal(model.instance$`buffer`, "EXPECTED_RESULT")
})

