# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GenericUDF")

model.instance <- GenericUDF$new()

test_that("udf_info_name", {
  # tests for the property `udf_info_name` (character)
  # name of UDFInfo to run, format is {namespace}/{udf_name}. Can not be used with exec

  # uncomment below to test the property 
  #expect_equal(model.instance$`udf_info_name`, "EXPECTED_RESULT")
})

test_that("language", {
  # tests for the property `language` (UDFLanguage)

  # uncomment below to test the property 
  #expect_equal(model.instance$`language`, "EXPECTED_RESULT")
})

test_that("version", {
  # tests for the property `version` (character)
  # Type-specific version

  # uncomment below to test the property 
  #expect_equal(model.instance$`version`, "EXPECTED_RESULT")
})

test_that("image_name", {
  # tests for the property `image_name` (character)
  # Docker image name to use for udf

  # uncomment below to test the property 
  #expect_equal(model.instance$`image_name`, "EXPECTED_RESULT")
})

test_that("exec", {
  # tests for the property `exec` (character)
  # Type-specific executable text

  # uncomment below to test the property 
  #expect_equal(model.instance$`exec`, "EXPECTED_RESULT")
})

test_that("exec_raw", {
  # tests for the property `exec_raw` (character)
  # optional raw text to store of serialized function, used for showing in UI

  # uncomment below to test the property 
  #expect_equal(model.instance$`exec_raw`, "EXPECTED_RESULT")
})

test_that("argument", {
  # tests for the property `argument` (character)
  # Argument(s) to pass to udf function, tuple or list of args/kwargs which can be in native or json format

  # uncomment below to test the property 
  #expect_equal(model.instance$`argument`, "EXPECTED_RESULT")
})

test_that("result_format", {
  # tests for the property `result_format` (UDFResultType)

  # uncomment below to test the property 
  #expect_equal(model.instance$`result_format`, "EXPECTED_RESULT")
})

test_that("task_name", {
  # tests for the property `task_name` (character)
  # name of task, optional

  # uncomment below to test the property 
  #expect_equal(model.instance$`task_name`, "EXPECTED_RESULT")
})

