# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ArrayTask")

model.instance <- ArrayTask$new()

test_that("id", {
  # tests for the property `id` (character)
  # task id

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # Optional task name

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)
  # Optional task description (Tasks purpose)

  # uncomment below to test the property 
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("array_metadata", {
  # tests for the property `array_metadata` (ArrayInfo)

  # uncomment below to test the property 
  #expect_equal(model.instance$`array_metadata`, "EXPECTED_RESULT")
})

test_that("subarray", {
  # tests for the property `subarray` (DomainArray)

  # uncomment below to test the property 
  #expect_equal(model.instance$`subarray`, "EXPECTED_RESULT")
})

test_that("memory", {
  # tests for the property `memory` (integer)
  # memory allocated to task in bytes

  # uncomment below to test the property 
  #expect_equal(model.instance$`memory`, "EXPECTED_RESULT")
})

test_that("cpu", {
  # tests for the property `cpu` (integer)
  # millicpu allocated to task

  # uncomment below to test the property 
  #expect_equal(model.instance$`cpu`, "EXPECTED_RESULT")
})

test_that("namespace", {
  # tests for the property `namespace` (character)
  # namespace task is tied to

  # uncomment below to test the property 
  #expect_equal(model.instance$`namespace`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (ArrayTaskStatus)

  # uncomment below to test the property 
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("start_time", {
  # tests for the property `start_time` (character)
  # Start time RFC3339 for job

  # uncomment below to test the property 
  #expect_equal(model.instance$`start_time`, "EXPECTED_RESULT")
})

test_that("finish_time", {
  # tests for the property `finish_time` (character)
  # Finish time RFC3339 for job

  # uncomment below to test the property 
  #expect_equal(model.instance$`finish_time`, "EXPECTED_RESULT")
})

test_that("cost", {
  # tests for the property `cost` (numeric)
  # Cost accumulated for task in USD, example is $0.12

  # uncomment below to test the property 
  #expect_equal(model.instance$`cost`, "EXPECTED_RESULT")
})

test_that("query_type", {
  # tests for the property `query_type` (Querytype)

  # uncomment below to test the property 
  #expect_equal(model.instance$`query_type`, "EXPECTED_RESULT")
})

test_that("udf_code", {
  # tests for the property `udf_code` (character)
  # Optional actual code that is going to be executed

  # uncomment below to test the property 
  #expect_equal(model.instance$`udf_code`, "EXPECTED_RESULT")
})

test_that("udf_language", {
  # tests for the property `udf_language` (character)
  # Optional actual language used to express udf_code

  # uncomment below to test the property 
  #expect_equal(model.instance$`udf_language`, "EXPECTED_RESULT")
})

test_that("sql_query", {
  # tests for the property `sql_query` (character)
  # Optional actual sql query that is going to be executed

  # uncomment below to test the property 
  #expect_equal(model.instance$`sql_query`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (ArrayTaskType)

  # uncomment below to test the property 
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("activity", {
  # tests for the property `activity` (array[ArrayActivityLog])
  # Array activity logs for task

  # uncomment below to test the property 
  #expect_equal(model.instance$`activity`, "EXPECTED_RESULT")
})

test_that("logs", {
  # tests for the property `logs` (character)
  # logs from array task

  # uncomment below to test the property 
  #expect_equal(model.instance$`logs`, "EXPECTED_RESULT")
})

