# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Query")

model.instance <- Query$new()

test_that("type", {
  # tests for the property `type` (Querytype)

  # uncomment below to test the property 
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("layout", {
  # tests for the property `layout` (Layout)

  # uncomment below to test the property 
  #expect_equal(model.instance$`layout`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (Querystatus)

  # uncomment below to test the property 
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("attributeBufferHeaders", {
  # tests for the property `attributeBufferHeaders` (array[AttributeBufferHeader])
  # List of attribute buffer headers

  # uncomment below to test the property 
  #expect_equal(model.instance$`attributeBufferHeaders`, "EXPECTED_RESULT")
})

test_that("writer", {
  # tests for the property `writer` (Writer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`writer`, "EXPECTED_RESULT")
})

test_that("reader", {
  # tests for the property `reader` (QueryReader)

  # uncomment below to test the property 
  #expect_equal(model.instance$`reader`, "EXPECTED_RESULT")
})

test_that("array", {
  # tests for the property `array` (Array)

  # uncomment below to test the property 
  #expect_equal(model.instance$`array`, "EXPECTED_RESULT")
})

test_that("totalFixedLengthBufferBytes", {
  # tests for the property `totalFixedLengthBufferBytes` (integer)
  # Total number of bytes in fixed size attribute buffers.

  # uncomment below to test the property 
  #expect_equal(model.instance$`totalFixedLengthBufferBytes`, "EXPECTED_RESULT")
})

test_that("totalVarLenBufferBytes", {
  # tests for the property `totalVarLenBufferBytes` (integer)
  # Total number of bytes in variable size attribute buffers.

  # uncomment below to test the property 
  #expect_equal(model.instance$`totalVarLenBufferBytes`, "EXPECTED_RESULT")
})

