# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ArrayTaskBrowserSidebar")

model.instance <- ArrayTaskBrowserSidebar$new()

test_that("organizations", {
  # tests for the property `organizations` (array[character])
  # list of all unique organizations the user is part of that have array tasks

  # uncomment below to test the property 
  #expect_equal(model.instance$`organizations`, "EXPECTED_RESULT")
})

test_that("result_count_for_all", {
  # tests for the property `result_count_for_all` (integer)
  # A count of \&quot;all\&quot;

  # uncomment below to test the property 
  #expect_equal(model.instance$`result_count_for_all`, "EXPECTED_RESULT")
})

test_that("result_count_by_namespace", {
  # tests for the property `result_count_by_namespace` (object)
  # A map that includes the result count by namespace

  # uncomment below to test the property 
  #expect_equal(model.instance$`result_count_by_namespace`, "EXPECTED_RESULT")
})

