# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MaxBufferSizes")

model.instance <- MaxBufferSizes$new()

test_that("maxBufferSizes", {
  # tests for the property `maxBufferSizes` (array[AttributeBufferSize])

  # uncomment below to test the property 
  #expect_equal(model.instance$`maxBufferSizes`, "EXPECTED_RESULT")
})

