# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ArrayTaskData")

model.instance <- ArrayTaskData$new()

test_that("array_tasks", {
  # tests for the property `array_tasks` (array[ArrayTask])
  # Array Tasks

  # uncomment below to test the property 
  #expect_equal(model.instance$`array_tasks`, "EXPECTED_RESULT")
})

test_that("pagination_metadata", {
  # tests for the property `pagination_metadata` (PaginationMetadata)

  # uncomment below to test the property 
  #expect_equal(model.instance$`pagination_metadata`, "EXPECTED_RESULT")
})

