# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Domain")

model.instance <- Domain$new()

test_that("type", {
  # tests for the property `type` (Datatype)

  # uncomment below to test the property 
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("tileOrder", {
  # tests for the property `tileOrder` (Layout)

  # uncomment below to test the property 
  #expect_equal(model.instance$`tileOrder`, "EXPECTED_RESULT")
})

test_that("cellOrder", {
  # tests for the property `cellOrder` (Layout)

  # uncomment below to test the property 
  #expect_equal(model.instance$`cellOrder`, "EXPECTED_RESULT")
})

test_that("dimensions", {
  # tests for the property `dimensions` (array[Dimension])
  # Array of dimensions

  # uncomment below to test the property 
  #expect_equal(model.instance$`dimensions`, "EXPECTED_RESULT")
})

