# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test FavoriteUpdate")

model.instance <- FavoriteUpdate$new()

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("namespace", {
  # tests for the property `namespace` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`namespace`, "EXPECTED_RESULT")
})

test_that("object_type", {
  # tests for the property `object_type` (FavoriteType)

  # uncomment below to test the property 
  #expect_equal(model.instance$`object_type`, "EXPECTED_RESULT")
})

