# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UDFInfo")

model.instance <- UDFInfo$new()

test_that("id", {
  # tests for the property `id` (character)
  # Unique id of udf

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # name of udf

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("language", {
  # tests for the property `language` (UDFLanguage)

  # uncomment below to test the property 
  #expect_equal(model.instance$`language`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (UDFType)

  # uncomment below to test the property 
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("readme", {
  # tests for the property `readme` (character)
  # Markdown readme of udfs

  # uncomment below to test the property 
  #expect_equal(model.instance$`readme`, "EXPECTED_RESULT")
})

test_that("license_id", {
  # tests for the property `license_id` (character)
  # License identifier from SPDX License List or Custom

  # uncomment below to test the property 
  #expect_equal(model.instance$`license_id`, "EXPECTED_RESULT")
})

test_that("license_text", {
  # tests for the property `license_text` (character)
  # License text

  # uncomment below to test the property 
  #expect_equal(model.instance$`license_text`, "EXPECTED_RESULT")
})

test_that("tags", {
  # tests for the property `tags` (array[character])
  # optional tags for udf

  # uncomment below to test the property 
  #expect_equal(model.instance$`tags`, "EXPECTED_RESULT")
})

