# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UDFSubarrayRange")

model.instance <- UDFSubarrayRange$new()

test_that("dimension_id", {
  # tests for the property `dimension_id` (integer)
  # The dimension index

  # uncomment below to test the property 
  #expect_equal(model.instance$`dimension_id`, "EXPECTED_RESULT")
})

test_that("range_start", {
  # tests for the property `range_start` (DimensionCoordinate)

  # uncomment below to test the property 
  #expect_equal(model.instance$`range_start`, "EXPECTED_RESULT")
})

test_that("range_end", {
  # tests for the property `range_end` (DimensionCoordinate)

  # uncomment below to test the property 
  #expect_equal(model.instance$`range_end`, "EXPECTED_RESULT")
})

