# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AWSAccessCredentials")

model.instance <- AWSAccessCredentials$new()

test_that("secret_access_key", {
  # tests for the property `secret_access_key` (character)
  # aws secret access key, never returned in get requests

  # uncomment below to test the property 
  #expect_equal(model.instance$`secret_access_key`, "EXPECTED_RESULT")
})

test_that("access_key_id", {
  # tests for the property `access_key_id` (character)
  # aws access key

  # uncomment below to test the property 
  #expect_equal(model.instance$`access_key_id`, "EXPECTED_RESULT")
})

test_that("service_role_arn", {
  # tests for the property `service_role_arn` (character)
  # aws service role to use for access

  # uncomment below to test the property 
  #expect_equal(model.instance$`service_role_arn`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # human readable name

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("default", {
  # tests for the property `default` (character)
  # true if this is the default credential to be used within this namespace

  # uncomment below to test the property 
  #expect_equal(model.instance$`default`, "EXPECTED_RESULT")
})

test_that("buckets", {
  # tests for the property `buckets` (array[character])
  # a whitelist of one or more buckets this key should access

  # uncomment below to test the property 
  #expect_equal(model.instance$`buckets`, "EXPECTED_RESULT")
})

test_that("created_at", {
  # tests for the property `created_at` (character)
  # Time when udf dependencies was created (rfc3339)

  # uncomment below to test the property 
  #expect_equal(model.instance$`created_at`, "EXPECTED_RESULT")
})

test_that("updated_at", {
  # tests for the property `updated_at` (character)
  # Time when udf dependencies was last updated (rfc3339)

  # uncomment below to test the property 
  #expect_equal(model.instance$`updated_at`, "EXPECTED_RESULT")
})

