# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UDFImageVersion")

model.instance <- UDFImageVersion$new()

test_that("id", {
  # tests for the property `id` (character)
  # Unique id of a versioned image

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # name of UDFImageVersion

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("udf_image_uuid", {
  # tests for the property `udf_image_uuid` (character)
  # Unique id of the udf image set

  # uncomment below to test the property 
  #expect_equal(model.instance$`udf_image_uuid`, "EXPECTED_RESULT")
})

test_that("docker_image", {
  # tests for the property `docker_image` (character)
  # Uri of docker image related to current entry

  # uncomment below to test the property 
  #expect_equal(model.instance$`docker_image`, "EXPECTED_RESULT")
})

test_that("version", {
  # tests for the property `version` (numeric)
  # Image-specific version

  # uncomment below to test the property 
  #expect_equal(model.instance$`version`, "EXPECTED_RESULT")
})

test_that("default", {
  # tests for the property `default` (character)
  # If current image is default version

  # uncomment below to test the property 
  #expect_equal(model.instance$`default`, "EXPECTED_RESULT")
})

test_that("latest", {
  # tests for the property `latest` (character)
  # If current image is latest version

  # uncomment below to test the property 
  #expect_equal(model.instance$`latest`, "EXPECTED_RESULT")
})

