# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SqlApi")

api.instance <- SqlApi$new()

test_that("RunSQL", {
  # tests for RunSQL
  # base path: http://localhost/v1
  # Run a sql query
  # @param namespace character namespace to run task under is in (an organization name or user's username)
  # @param sql SQLParameters sql being submitted
  # @param accept.encoding character Encoding to use (optional)
  # @return [array[object]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

