# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InvitationOrganizationJoinEmail")

model.instance <- InvitationOrganizationJoinEmail$new()

test_that("actions", {
  # tests for the property `actions` (array[NamespaceActions])
  # List of permitted actions

  # uncomment below to test the property 
  #expect_equal(model.instance$`actions`, "EXPECTED_RESULT")
})

test_that("organization_role", {
  # tests for the property `organization_role` (OrganizationRoles)

  # uncomment below to test the property 
  #expect_equal(model.instance$`organization_role`, "EXPECTED_RESULT")
})

test_that("invitee_email", {
  # tests for the property `invitee_email` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`invitee_email`, "EXPECTED_RESULT")
})

