# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SQLParameters")

model.instance <- SQLParameters$new()

test_that("name", {
  # tests for the property `name` (character)
  # name of task, optional

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("query", {
  # tests for the property `query` (character)
  # query to run

  # uncomment below to test the property 
  #expect_equal(model.instance$`query`, "EXPECTED_RESULT")
})

test_that("output_uri", {
  # tests for the property `output_uri` (character)
  # Output array uri

  # uncomment below to test the property 
  #expect_equal(model.instance$`output_uri`, "EXPECTED_RESULT")
})

