# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ArrayMetadata")

model.instance <- ArrayMetadata$new()

test_that("ranges", {
  # tests for the property `ranges` (array[ArrayMetadataEntry])
  # List of metadata entries

  # uncomment below to test the property 
  #expect_equal(model.instance$`ranges`, "EXPECTED_RESULT")
})

