# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Writer")

model.instance <- Writer$new()

test_that("checkCoordDups", {
  # tests for the property `checkCoordDups` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`checkCoordDups`, "EXPECTED_RESULT")
})

test_that("checkCoordOOB", {
  # tests for the property `checkCoordOOB` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`checkCoordOOB`, "EXPECTED_RESULT")
})

test_that("dedupCoords", {
  # tests for the property `dedupCoords` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`dedupCoords`, "EXPECTED_RESULT")
})

test_that("subarray", {
  # tests for the property `subarray` (DomainArray)

  # uncomment below to test the property 
  #expect_equal(model.instance$`subarray`, "EXPECTED_RESULT")
})

