# TileDB Storage Platform API
#
# TileDB Storage Platform REST API
#
# The version of the OpenAPI document: 2.1.26
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Favorite
#'
#' @description Favorite Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character [optional]
#'
#' @field object_type  \link{FavoriteType} [optional]
#'
#' @field namespace  character [optional]
#'
#' @field name  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Favorite <- R6::R6Class(
  'Favorite',
  public = list(
    `id` = NULL,
    `object_type` = NULL,
    `namespace` = NULL,
    `name` = NULL,
    initialize = function(
        `id`=NULL, `object_type`=NULL, `namespace`=NULL, `name`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`object_type`)) {
        stopifnot(R6::is.R6(`object_type`))
        self$`object_type` <- `object_type`
      }
      if (!is.null(`namespace`)) {
        stopifnot(is.character(`namespace`), length(`namespace`) == 1)
        self$`namespace` <- `namespace`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
    },
    toJSON = function() {
      FavoriteObject <- list()
      if (!is.null(self$`id`)) {
        FavoriteObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`object_type`)) {
        FavoriteObject[['object_type']] <-
          self$`object_type`$toJSON()
      }
      if (!is.null(self$`namespace`)) {
        FavoriteObject[['namespace']] <-
          self$`namespace`
      }
      if (!is.null(self$`name`)) {
        FavoriteObject[['name']] <-
          self$`name`
      }

      FavoriteObject
    },
    fromJSON = function(FavoriteJson) {
      FavoriteObject <- jsonlite::fromJSON(FavoriteJson)
      if (!is.null(FavoriteObject$`id`)) {
        self$`id` <- FavoriteObject$`id`
      }
      if (!is.null(FavoriteObject$`object_type`)) {
        object_typeObject <- FavoriteType$new()
        object_typeObject$fromJSON(jsonlite::toJSON(FavoriteObject$object_type, auto_unbox = TRUE, digits = NA))
        self$`object_type` <- object_typeObject
      }
      if (!is.null(FavoriteObject$`namespace`)) {
        self$`namespace` <- FavoriteObject$`namespace`
      }
      if (!is.null(FavoriteObject$`name`)) {
        self$`name` <- FavoriteObject$`name`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`object_type`)) {
        sprintf(
        '"object_type":
        %s
        ',
        jsonlite::toJSON(self$`object_type`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`namespace`)) {
        sprintf(
        '"namespace":
          "%s"
                ',
        self$`namespace`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(FavoriteJson) {
      FavoriteObject <- jsonlite::fromJSON(FavoriteJson)
      self$`id` <- FavoriteObject$`id`
      self$`object_type` <- FavoriteType$new()$fromJSON(jsonlite::toJSON(FavoriteObject$object_type, auto_unbox = TRUE, digits = NA))
      self$`namespace` <- FavoriteObject$`namespace`
      self$`name` <- FavoriteObject$`name`
      self
    }
  )
)

