# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InvitationData")

model.instance <- InvitationData$new()

test_that("invitations", {
  # tests for the property `invitations` (array[Invitation])
  # List of invitations

  # uncomment below to test the property 
  #expect_equal(model.instance$`invitations`, "EXPECTED_RESULT")
})

test_that("pagination_metadata", {
  # tests for the property `pagination_metadata` (PaginationMetadata)

  # uncomment below to test the property 
  #expect_equal(model.instance$`pagination_metadata`, "EXPECTED_RESULT")
})

