# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Token")

model.instance <- Token$new()

test_that("token", {
  # tests for the property `token` (character)
  # A api token

  # uncomment below to test the property 
  #expect_equal(model.instance$`token`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # Name of token to revoke

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("issued_at", {
  # tests for the property `issued_at` (character)
  # datetime the token was created at

  # uncomment below to test the property 
  #expect_equal(model.instance$`issued_at`, "EXPECTED_RESULT")
})

test_that("expires_at", {
  # tests for the property `expires_at` (character)
  # datetime the token when token will expire

  # uncomment below to test the property 
  #expect_equal(model.instance$`expires_at`, "EXPECTED_RESULT")
})

test_that("scope", {
  # tests for the property `scope` (character)
  # Optional scope to limit token, defaults to all permissions, current supported values are password_reset or *

  # uncomment below to test the property 
  #expect_equal(model.instance$`scope`, "EXPECTED_RESULT")
})

