# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ArrayInfoUpdate")

model.instance <- ArrayInfoUpdate$new()

test_that("description", {
  # tests for the property `description` (character)
  # description of array

  # uncomment below to test the property 
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # description of array

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("uri", {
  # tests for the property `uri` (character)
  # uri of array

  # uncomment below to test the property 
  #expect_equal(model.instance$`uri`, "EXPECTED_RESULT")
})

test_that("file_type", {
  # tests for the property `file_type` (FileType)

  # uncomment below to test the property 
  #expect_equal(model.instance$`file_type`, "EXPECTED_RESULT")
})

test_that("file_properties", {
  # tests for the property `file_properties` (map(character))
  # map of file properties created for this array

  # uncomment below to test the property 
  #expect_equal(model.instance$`file_properties`, "EXPECTED_RESULT")
})

test_that("access_credentials_name", {
  # tests for the property `access_credentials_name` (character)
  # the name of the access credentials to use. if unset, the default credentials will be used

  # uncomment below to test the property 
  #expect_equal(model.instance$`access_credentials_name`, "EXPECTED_RESULT")
})

test_that("logo", {
  # tests for the property `logo` (character)
  # logo (base64 encoded) for the array. Optional

  # uncomment below to test the property 
  #expect_equal(model.instance$`logo`, "EXPECTED_RESULT")
})

test_that("tags", {
  # tests for the property `tags` (array[character])
  # optional tags for array

  # uncomment below to test the property 
  #expect_equal(model.instance$`tags`, "EXPECTED_RESULT")
})

test_that("license_id", {
  # tests for the property `license_id` (character)
  # License identifier from SPDX License List or Custom

  # uncomment below to test the property 
  #expect_equal(model.instance$`license_id`, "EXPECTED_RESULT")
})

test_that("license_text", {
  # tests for the property `license_text` (character)
  # License text

  # uncomment below to test the property 
  #expect_equal(model.instance$`license_text`, "EXPECTED_RESULT")
})

test_that("read_only", {
  # tests for the property `read_only` (character)
  # Suggests if the array is in read_only mode

  # uncomment below to test the property 
  #expect_equal(model.instance$`read_only`, "EXPECTED_RESULT")
})

