# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ArrayActivityLog")

model.instance <- ArrayActivityLog$new()

test_that("event_at", {
  # tests for the property `event_at` (character)
  # time event took place (RFC3339)

  # uncomment below to test the property 
  #expect_equal(model.instance$`event_at`, "EXPECTED_RESULT")
})

test_that("action", {
  # tests for the property `action` (ActivityEventType)

  # uncomment below to test the property 
  #expect_equal(model.instance$`action`, "EXPECTED_RESULT")
})

test_that("username", {
  # tests for the property `username` (character)
  # User who performed action

  # uncomment below to test the property 
  #expect_equal(model.instance$`username`, "EXPECTED_RESULT")
})

test_that("bytes_sent", {
  # tests for the property `bytes_sent` (integer)
  # Bytes sent to client

  # uncomment below to test the property 
  #expect_equal(model.instance$`bytes_sent`, "EXPECTED_RESULT")
})

test_that("bytes_received", {
  # tests for the property `bytes_received` (integer)
  # Bytes recieved from client

  # uncomment below to test the property 
  #expect_equal(model.instance$`bytes_received`, "EXPECTED_RESULT")
})

test_that("array_task_id", {
  # tests for the property `array_task_id` (character)
  # uuid of associated array task

  # uncomment below to test the property 
  #expect_equal(model.instance$`array_task_id`, "EXPECTED_RESULT")
})

test_that("query_ranges", {
  # tests for the property `query_ranges` (character)
  # ranges for query

  # uncomment below to test the property 
  #expect_equal(model.instance$`query_ranges`, "EXPECTED_RESULT")
})

