# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ReadState")

model.instance <- ReadState$new()

test_that("initialized", {
  # tests for the property `initialized` (character)
  # True if the reader has been initialized.

  # uncomment below to test the property 
  #expect_equal(model.instance$`initialized`, "EXPECTED_RESULT")
})

test_that("overflowed", {
  # tests for the property `overflowed` (character)
  # True if the query produced results that could not fit in some buffer.

  # uncomment below to test the property 
  #expect_equal(model.instance$`overflowed`, "EXPECTED_RESULT")
})

test_that("unsplittable", {
  # tests for the property `unsplittable` (character)
  # True if the current subarray partition is unsplittable.

  # uncomment below to test the property 
  #expect_equal(model.instance$`unsplittable`, "EXPECTED_RESULT")
})

test_that("subarrayPartitioner", {
  # tests for the property `subarrayPartitioner` (SubarrayPartitioner)

  # uncomment below to test the property 
  #expect_equal(model.instance$`subarrayPartitioner`, "EXPECTED_RESULT")
})

