# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrganizationUser")

model.instance <- OrganizationUser$new()

test_that("user_id", {
  # tests for the property `user_id` (character)
  # unique id of user

  # uncomment below to test the property 
  #expect_equal(model.instance$`user_id`, "EXPECTED_RESULT")
})

test_that("organization_id", {
  # tests for the property `organization_id` (character)
  # unique id of organization

  # uncomment below to test the property 
  #expect_equal(model.instance$`organization_id`, "EXPECTED_RESULT")
})

test_that("username", {
  # tests for the property `username` (character)
  # username for user

  # uncomment below to test the property 
  #expect_equal(model.instance$`username`, "EXPECTED_RESULT")
})

test_that("organization_name", {
  # tests for the property `organization_name` (character)
  # name of organization

  # uncomment below to test the property 
  #expect_equal(model.instance$`organization_name`, "EXPECTED_RESULT")
})

test_that("role", {
  # tests for the property `role` (OrganizationRoles)

  # uncomment below to test the property 
  #expect_equal(model.instance$`role`, "EXPECTED_RESULT")
})

test_that("allowed_actions", {
  # tests for the property `allowed_actions` (array[NamespaceActions])
  # list of actions user is allowed to do on this organization

  # uncomment below to test the property 
  #expect_equal(model.instance$`allowed_actions`, "EXPECTED_RESULT")
})

