# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ArrayTasksApi")

api.instance <- ArrayTasksApi$new()

test_that("GetArrayTasksSidebar", {
  # tests for GetArrayTasksSidebar
  # base path: http://localhost/v1
  # @param start integer Fetch tasks created after this time, unix epoch in seconds, default 7 days ago (optional)
  # @param end integer Fetch tasks created before this time, unix epoch in seconds, default now (optional)
  # @return [ArrayTaskBrowserSidebar]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

