# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Organization")

model.instance <- Organization$new()

test_that("id", {
  # tests for the property `id` (character)
  # unique id of organization

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("role", {
  # tests for the property `role` (OrganizationRoles)

  # uncomment below to test the property 
  #expect_equal(model.instance$`role`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # organization name must be unique

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("created_at", {
  # tests for the property `created_at` (character)
  # Datetime organization was created in UTC

  # uncomment below to test the property 
  #expect_equal(model.instance$`created_at`, "EXPECTED_RESULT")
})

test_that("updated_at", {
  # tests for the property `updated_at` (character)
  # Datetime organization was updated in UTC

  # uncomment below to test the property 
  #expect_equal(model.instance$`updated_at`, "EXPECTED_RESULT")
})

test_that("logo", {
  # tests for the property `logo` (character)
  # Organization logo

  # uncomment below to test the property 
  #expect_equal(model.instance$`logo`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)
  # Organization description

  # uncomment below to test the property 
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("users", {
  # tests for the property `users` (array[OrganizationUser])

  # uncomment below to test the property 
  #expect_equal(model.instance$`users`, "EXPECTED_RESULT")
})

test_that("allowed_actions", {
  # tests for the property `allowed_actions` (array[NamespaceActions])
  # list of actions user is allowed to do on this organization

  # uncomment below to test the property 
  #expect_equal(model.instance$`allowed_actions`, "EXPECTED_RESULT")
})

test_that("num_of_arrays", {
  # tests for the property `num_of_arrays` (numeric)
  # number of registered arrays for this organization

  # uncomment below to test the property 
  #expect_equal(model.instance$`num_of_arrays`, "EXPECTED_RESULT")
})

test_that("enabled_features", {
  # tests for the property `enabled_features` (array[character])
  # List of extra/optional/beta features to enable for namespace

  # uncomment below to test the property 
  #expect_equal(model.instance$`enabled_features`, "EXPECTED_RESULT")
})

test_that("unpaid_subscription", {
  # tests for the property `unpaid_subscription` (character)
  # A notice that the user has an unpaid subscription

  # uncomment below to test the property 
  #expect_equal(model.instance$`unpaid_subscription`, "EXPECTED_RESULT")
})

test_that("notebook_settings", {
  # tests for the property `notebook_settings` (NotebookSettings)

  # uncomment below to test the property 
  #expect_equal(model.instance$`notebook_settings`, "EXPECTED_RESULT")
})

