# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Pricing")

model.instance <- Pricing$new()

test_that("id", {
  # tests for the property `id` (character)
  # Unique id of plan as defined by Stripe

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("array_uuid", {
  # tests for the property `array_uuid` (character)
  # Unique id of registered array

  # uncomment below to test the property 
  #expect_equal(model.instance$`array_uuid`, "EXPECTED_RESULT")
})

test_that("pricing_name", {
  # tests for the property `pricing_name` (character)
  # Name of pricing

  # uncomment below to test the property 
  #expect_equal(model.instance$`pricing_name`, "EXPECTED_RESULT")
})

test_that("pricing_type", {
  # tests for the property `pricing_type` (PricingType)

  # uncomment below to test the property 
  #expect_equal(model.instance$`pricing_type`, "EXPECTED_RESULT")
})

test_that("product_name", {
  # tests for the property `product_name` (character)
  # Name of product

  # uncomment below to test the property 
  #expect_equal(model.instance$`product_name`, "EXPECTED_RESULT")
})

test_that("product_statement_descriptor", {
  # tests for the property `product_statement_descriptor` (character)
  # Extra information about a product which will appear on the credit card statement of the customer

  # uncomment below to test the property 
  #expect_equal(model.instance$`product_statement_descriptor`, "EXPECTED_RESULT")
})

test_that("product_unit_label", {
  # tests for the property `product_unit_label` (PricingUnitLabel)

  # uncomment below to test the property 
  #expect_equal(model.instance$`product_unit_label`, "EXPECTED_RESULT")
})

test_that("currency", {
  # tests for the property `currency` (PricingCurrency)

  # uncomment below to test the property 
  #expect_equal(model.instance$`currency`, "EXPECTED_RESULT")
})

test_that("aggregate_usage", {
  # tests for the property `aggregate_usage` (PricingAggregateUsage)

  # uncomment below to test the property 
  #expect_equal(model.instance$`aggregate_usage`, "EXPECTED_RESULT")
})

test_that("interval", {
  # tests for the property `interval` (PricingInterval)

  # uncomment below to test the property 
  #expect_equal(model.instance$`interval`, "EXPECTED_RESULT")
})

test_that("divided_by", {
  # tests for the property `divided_by` (integer)
  # Group of n product unit labels

  # uncomment below to test the property 
  #expect_equal(model.instance$`divided_by`, "EXPECTED_RESULT")
})

test_that("charge", {
  # tests for the property `charge` (numeric)
  # Price in cents (decimal) per unitlabel

  # uncomment below to test the property 
  #expect_equal(model.instance$`charge`, "EXPECTED_RESULT")
})

test_that("activated", {
  # tests for the property `activated` (character)
  # If pricing is activated

  # uncomment below to test the property 
  #expect_equal(model.instance$`activated`, "EXPECTED_RESULT")
})

