# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Subscription")

model.instance <- Subscription$new()

test_that("id", {
  # tests for the property `id` (character)
  # Unique id of subscription as defined by Stripe

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("owner_namespace_uuid", {
  # tests for the property `owner_namespace_uuid` (character)
  # Unique id of the array (product) owner

  # uncomment below to test the property 
  #expect_equal(model.instance$`owner_namespace_uuid`, "EXPECTED_RESULT")
})

test_that("customer_namespace_uuid", {
  # tests for the property `customer_namespace_uuid` (character)
  # Unique id of the array (product) user (customer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`customer_namespace_uuid`, "EXPECTED_RESULT")
})

test_that("pricing", {
  # tests for the property `pricing` (array[Pricing])
  # list of pricing used by this subscription

  # uncomment below to test the property 
  #expect_equal(model.instance$`pricing`, "EXPECTED_RESULT")
})

