# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UDFInfoVersion")

model.instance <- UDFInfoVersion$new()

test_that("id", {
  # tests for the property `id` (character)
  # Unique id of a versioned udf

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("udf_image_uuid", {
  # tests for the property `udf_image_uuid` (character)
  # Unique id of the versioned image used by current udf version

  # uncomment below to test the property 
  #expect_equal(model.instance$`udf_image_uuid`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # name of udf version

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("version", {
  # tests for the property `version` (character)
  # Type-specific version

  # uncomment below to test the property 
  #expect_equal(model.instance$`version`, "EXPECTED_RESULT")
})

test_that("image_name", {
  # tests for the property `image_name` (character)
  # Docker image name to use for udf

  # uncomment below to test the property 
  #expect_equal(model.instance$`image_name`, "EXPECTED_RESULT")
})

test_that("exec", {
  # tests for the property `exec` (character)
  # Type-specific executable text

  # uncomment below to test the property 
  #expect_equal(model.instance$`exec`, "EXPECTED_RESULT")
})

test_that("exec_raw", {
  # tests for the property `exec_raw` (character)
  # optional raw text to store of serialized function, used for showing in UI

  # uncomment below to test the property 
  #expect_equal(model.instance$`exec_raw`, "EXPECTED_RESULT")
})

test_that("default", {
  # tests for the property `default` (character)
  # If current image version is default version

  # uncomment below to test the property 
  #expect_equal(model.instance$`default`, "EXPECTED_RESULT")
})

