# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Favorite")

model.instance <- Favorite$new()

test_that("id", {
  # tests for the property `id` (character)
  # unique uuid of the favorite 

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("object_type", {
  # tests for the property `object_type` (FavoriteType)

  # uncomment below to test the property 
  #expect_equal(model.instance$`object_type`, "EXPECTED_RESULT")
})

test_that("namespace", {
  # tests for the property `namespace` (character)
  # The namespace the favorite is in. It won&#39;t be persisted in DB

  # uncomment below to test the property 
  #expect_equal(model.instance$`namespace`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # Name of the object. It wont be persisted in DB

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

