# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ArrayMetadata")

model.instance <- ArrayMetadata$new()

test_that("entries", {
  # tests for the property `entries` (array[ArrayMetadataEntry])
  # List of metadata entries

  # uncomment below to test the property 
  #expect_equal(model.instance$`entries`, "EXPECTED_RESULT")
})

