# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test FavoritesApi")

api.instance <- FavoritesApi$new()

test_that("DeleteFavoriteId", {
  # tests for DeleteFavoriteId
  # base path: http://localhost/v1
  # Delete specific favorite
  # @param id character The uuid of the favorite
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetFavorite", {
  # tests for GetFavorite
  # base path: http://localhost/v1
  # Fetch specific favorite of a user
  # @param id character The uuid of the favorite
  # @return [Favorite]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetFavorites", {
  # tests for GetFavorites
  # base path: http://localhost/v1
  # Fetch all favorites of connected user
  # @param type character The type of the desired favorites e.g. arrays (optional)
  # @return [array[Favorite]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PostFavorite", {
  # tests for PostFavorite
  # base path: http://localhost/v1
  # Add a new favorite
  # @param body FavoriteUpdate  (optional)
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

