# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UDFArrayDetails")

model.instance <- UDFArrayDetails$new()

test_that("uri", {
  # tests for the property `uri` (character)
  # array to set ranges and buffers on, must be in tiledb:// format

  # uncomment below to test the property 
  #expect_equal(model.instance$`uri`, "EXPECTED_RESULT")
})

test_that("ranges", {
  # tests for the property `ranges` (QueryRanges)

  # uncomment below to test the property 
  #expect_equal(model.instance$`ranges`, "EXPECTED_RESULT")
})

test_that("buffers", {
  # tests for the property `buffers` (array[character])
  # List of buffers to fetch (attributes + dimensions)

  # uncomment below to test the property 
  #expect_equal(model.instance$`buffers`, "EXPECTED_RESULT")
})

