# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InvitationArrayShareEmail")

model.instance <- InvitationArrayShareEmail$new()

test_that("actions", {
  # tests for the property `actions` (array[ArrayActions])
  # List of permitted actions

  # uncomment below to test the property 
  #expect_equal(model.instance$`actions`, "EXPECTED_RESULT")
})

test_that("invitee_email", {
  # tests for the property `invitee_email` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`invitee_email`, "EXPECTED_RESULT")
})

