# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ArrayInfo")

model.instance <- ArrayInfo$new()

test_that("id", {
  # tests for the property `id` (character)
  # unique id of registered array

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("file_type", {
  # tests for the property `file_type` (FileType)

  # uncomment below to test the property 
  #expect_equal(model.instance$`file_type`, "EXPECTED_RESULT")
})

test_that("file_properties", {
  # tests for the property `file_properties` (map(character))
  # map of file properties created for this array

  # uncomment below to test the property 
  #expect_equal(model.instance$`file_properties`, "EXPECTED_RESULT")
})

test_that("uri", {
  # tests for the property `uri` (character)
  # uri of array

  # uncomment below to test the property 
  #expect_equal(model.instance$`uri`, "EXPECTED_RESULT")
})

test_that("namespace", {
  # tests for the property `namespace` (character)
  # namespace array is in

  # uncomment below to test the property 
  #expect_equal(model.instance$`namespace`, "EXPECTED_RESULT")
})

test_that("size", {
  # tests for the property `size` (numeric)
  # size in bytes of array

  # uncomment below to test the property 
  #expect_equal(model.instance$`size`, "EXPECTED_RESULT")
})

test_that("last_accessed", {
  # tests for the property `last_accessed` (character)
  # Datetime array was last accessed in UTC

  # uncomment below to test the property 
  #expect_equal(model.instance$`last_accessed`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)
  # description of array

  # uncomment below to test the property 
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # name of array

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("allowed_actions", {
  # tests for the property `allowed_actions` (array[ArrayActions])
  # list of actions user is allowed to do on this array

  # uncomment below to test the property 
  #expect_equal(model.instance$`allowed_actions`, "EXPECTED_RESULT")
})

test_that("pricing", {
  # tests for the property `pricing` (array[Pricing])
  # list of pricing created for this array

  # uncomment below to test the property 
  #expect_equal(model.instance$`pricing`, "EXPECTED_RESULT")
})

test_that("subscriptions", {
  # tests for the property `subscriptions` (array[Subscription])
  # list of subscriptions created for this array

  # uncomment below to test the property 
  #expect_equal(model.instance$`subscriptions`, "EXPECTED_RESULT")
})

test_that("logo", {
  # tests for the property `logo` (character)
  # logo (base64 encoded) for the array. Optional

  # uncomment below to test the property 
  #expect_equal(model.instance$`logo`, "EXPECTED_RESULT")
})

test_that("access_credentials_name", {
  # tests for the property `access_credentials_name` (character)
  # the name of the access credentials to use. if unset, the default credentials will be used

  # uncomment below to test the property 
  #expect_equal(model.instance$`access_credentials_name`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (character)
  # Array type (dense, key-value, sparse)

  # uncomment below to test the property 
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("share_count", {
  # tests for the property `share_count` (numeric)
  # number of unique namespaces this array is shared with

  # uncomment below to test the property 
  #expect_equal(model.instance$`share_count`, "EXPECTED_RESULT")
})

test_that("public_share", {
  # tests for the property `public_share` (character)
  # Suggests if the array was shared to public by owner

  # uncomment below to test the property 
  #expect_equal(model.instance$`public_share`, "EXPECTED_RESULT")
})

test_that("namespace_subscribed", {
  # tests for the property `namespace_subscribed` (character)
  # Depends on the namespace asking, denotes the existence of subscription of namespace to this array

  # uncomment below to test the property 
  #expect_equal(model.instance$`namespace_subscribed`, "EXPECTED_RESULT")
})

test_that("tiledb_uri", {
  # tests for the property `tiledb_uri` (character)
  # uri for access through TileDB cloud

  # uncomment below to test the property 
  #expect_equal(model.instance$`tiledb_uri`, "EXPECTED_RESULT")
})

test_that("tags", {
  # tests for the property `tags` (array[character])
  # optional tags for array

  # uncomment below to test the property 
  #expect_equal(model.instance$`tags`, "EXPECTED_RESULT")
})

test_that("license_id", {
  # tests for the property `license_id` (character)
  # License identifier from SPDX License List or Custom

  # uncomment below to test the property 
  #expect_equal(model.instance$`license_id`, "EXPECTED_RESULT")
})

test_that("license_text", {
  # tests for the property `license_text` (character)
  # License text

  # uncomment below to test the property 
  #expect_equal(model.instance$`license_text`, "EXPECTED_RESULT")
})

test_that("read_only", {
  # tests for the property `read_only` (character)
  # Suggests if the array is in read_only mode

  # uncomment below to test the property 
  #expect_equal(model.instance$`read_only`, "EXPECTED_RESULT")
})

test_that("is_favorite", {
  # tests for the property `is_favorite` (character)
  # Indicates whether the array is in user favorites

  # uncomment below to test the property 
  #expect_equal(model.instance$`is_favorite`, "EXPECTED_RESULT")
})

test_that("favorite_uuid", {
  # tests for the property `favorite_uuid` (character)
  # The favorite UUID if the array if is_favorite is true

  # uncomment below to test the property 
  #expect_equal(model.instance$`favorite_uuid`, "EXPECTED_RESULT")
})

