# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ArrayApi")

api.instance <- ArrayApi$new()

test_that("ArrayActivityLog", {
  # tests for ArrayActivityLog
  # base path: http://localhost/v1
  # get array activity logs
  # @param namespace character namespace array is in (an organization name or user's username)
  # @param array character name/uri of array that is url-encoded
  # @param start integer Start time of window of fetch logs, unix epoch in seconds (default: seven days ago) (optional)
  # @param end integer End time of window of fetch logs, unix epoch in seconds (default: current utc timestamp) (optional)
  # @param event.types character Event values can be one or more of the following read, write, create, delete, register, deregister, comma separated (optional)
  # @param task.id character Array task id To filter activity to (optional)
  # @param has.task.id character Excludes activity log results that does not contain an array task uuid (optional)
  # @return [array[ArrayActivityLog]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ArraysBrowserOwnedGet", {
  # tests for ArraysBrowserOwnedGet
  # base path: http://localhost/v1
  # Fetch a list of all arrays that are owned directly by user or user&#39;s organizations
  # @param page integer pagination offset (optional)
  # @param per.page integer pagination limit (optional)
  # @param search character search string that will look at name, namespace or description fields (optional)
  # @param namespace character namespace (optional)
  # @param orderby character sort by which field valid values include last_accessed, size, name (optional)
  # @param permissions character permissions valid values include read, read_write, write, admin (optional)
  # @param tag array[character] tag to search for, more than one can be included (optional)
  # @param exclude.tag array[character] tags to exclude matching array in results, more than one can be included (optional)
  # @param file.type array[character] file_type to search for, more than one can be included (optional)
  # @param exclude.file.type array[character] file_type to exclude matching array in results, more than one can be included (optional)
  # @param file.property array[character] file_property key-value pair (comma separated, i.e. key,value) to search for, more than one can be included (optional)
  # @return [ArrayBrowserData]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ArraysBrowserOwnedSidebarGet", {
  # tests for ArraysBrowserOwnedSidebarGet
  # base path: http://localhost/v1
  # Fetch a sidebar for arrays that are owned directly by user or user&#39;s organizations
  # @return [ArrayBrowserSidebar]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ArraysBrowserPublicGet", {
  # tests for ArraysBrowserPublicGet
  # base path: http://localhost/v1
  # Fetch a list of all arrays that have been shared publically
  # @param page integer pagination offset (optional)
  # @param per.page integer pagination limit (optional)
  # @param search character search string that will look at name, namespace or description fields (optional)
  # @param namespace character namespace (optional)
  # @param orderby character sort by which field valid values include last_accessed, size, name (optional)
  # @param permissions character permissions valid values include read, read_write, write, admin (optional)
  # @param tag array[character] tag to search for, more than one can be included (optional)
  # @param exclude.tag array[character] tags to exclude matching array in results, more than one can be included (optional)
  # @param file.type array[character] file_type to search for, more than one can be included (optional)
  # @param exclude.file.type array[character] file_type to exclude matching array in results, more than one can be included (optional)
  # @param file.property array[character] file_property key-value pair (comma separated, i.e. key,value) to search for, more than one can be included (optional)
  # @return [ArrayBrowserData]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ArraysBrowserPublicSidebarGet", {
  # tests for ArraysBrowserPublicSidebarGet
  # base path: http://localhost/v1
  # Fetch a sidebar of all arrays that have been shared publically
  # @return [ArrayBrowserSidebar]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ArraysBrowserSharedGet", {
  # tests for ArraysBrowserSharedGet
  # base path: http://localhost/v1
  # Fetch a list of all arrays that have been shared with the user
  # @param page integer pagination offset (optional)
  # @param per.page integer pagination limit (optional)
  # @param search character search string that will look at name, namespace or description fields (optional)
  # @param namespace character namespace (optional)
  # @param orderby character sort by which field valid values include last_accessed, size, name (optional)
  # @param permissions character permissions valid values include read, read_write, write, admin (optional)
  # @param tag array[character] tag to search for, more than one can be included (optional)
  # @param exclude.tag array[character] tags to exclude matching array in results, more than one can be included (optional)
  # @param file.type array[character] file_type to search for, more than one can be included (optional)
  # @param exclude.file.type array[character] file_type to exclude matching array in results, more than one can be included (optional)
  # @param file.property array[character] file_property key-value pair (comma separated, i.e. key,value) to search for, more than one can be included (optional)
  # @return [ArrayBrowserData]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ArraysBrowserSharedSidebarGet", {
  # tests for ArraysBrowserSharedSidebarGet
  # base path: http://localhost/v1
  # Fetch a list of all arrays that have been shared with the user
  # @return [ArrayBrowserSidebar]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ArraysNamespaceArrayEndTimestampsGet", {
  # tests for ArraysNamespaceArrayEndTimestampsGet
  # base path: http://localhost/v1
  # retrieve a list of timestamps from the array fragment info listing in milliseconds, paginated
  # @param namespace character namespace array is in (an organization name or user's username)
  # @param array character name/uri of array that is url-encoded
  # @param page integer pagination offset (optional)
  # @param per.page integer pagination limit (optional)
  # @return [ArrayEndTimestampData]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ConsolidateArray", {
  # tests for ConsolidateArray
  # base path: http://localhost/v1
  # consolidate an array at a specified URI
  # @param namespace character namespace array is in (an organization name or user's username)
  # @param array character name/uri of array that is url-encoded
  # @param tiledb.config TileDBConfig tiledb configuration
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CreateArray", {
  # tests for CreateArray
  # base path: http://localhost/v1
  # create a array schema at a specified URI registered to a group/project
  # @param namespace character namespace array is in (an organization name or user's username)
  # @param array character name/uri of array that is url-encoded
  # @param content.type character Content Type of input and return mime
  # @param array.schema ArraySchema ArraySchema being created
  # @param X_TILEDB_CLOUD_ACCESS_CREDENTIALS_NAME character Optional registered access credentials to use for creation (optional)
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteArray", {
  # tests for DeleteArray
  # base path: http://localhost/v1
  # delete a array
  # @param namespace character namespace array is in (an organization name or user's username)
  # @param array character name/uri of array that is url-encoded
  # @param content.type character Content Type of input and return mime
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeregisterArray", {
  # tests for DeregisterArray
  # base path: http://localhost/v1
  # deregister a array
  # @param namespace character namespace array is in (an organization name or user's username)
  # @param array character name/uri of array that is url-encoded
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetActivityLogById", {
  # tests for GetActivityLogById
  # base path: http://localhost/v1
  # get activity log by id
  # @param namespace character namespace array is in (an organization name or user's username)
  # @param array character name/uri of array that is url-encoded
  # @param id character id of the activity
  # @return [ArrayActivityLog]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetAllArrayMetadata", {
  # tests for GetAllArrayMetadata
  # base path: http://localhost/v1
  # get all array metadata user has access to
  # @param public.share character Public share values can be one of exclude, only (optional)
  # @return [array[ArrayInfo]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetArray", {
  # tests for GetArray
  # base path: http://localhost/v1
  # get an ArraySchema using a url encoded uri
  # @param namespace character namespace array is in (an organization name or user's username)
  # @param array character name/uri of array that is url-encoded
  # @param content.type character Content Type of input and return mime
  # @return [ArraySchema]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetArrayMaxBufferSizes", {
  # tests for GetArrayMaxBufferSizes
  # base path: http://localhost/v1
  # get the max buffer sizes of an array for a subarray
  # @param namespace character namespace array is in (an organization name or user's username)
  # @param array character name/uri of array that is url-encoded
  # @param subarray character CSV string of subarray to get max buffer sizes for
  # @param content.type character Content Type of input and return mime
  # @param x.payer character Name of organization or user who should be charged for this request (optional)
  # @return [MaxBufferSizes]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetArrayMetaDataJson", {
  # tests for GetArrayMetaDataJson
  # base path: http://localhost/v1
  # get metadata from the array in json format
  # @param namespace character namespace array is in (an organization name or user's username)
  # @param array character name/uri of array that is url-encoded
  # @param length integer (optional) limit character length of returned values (optional)
  # @param end.timestamp integer Milliseconds since Unix epoch, metadata will use open_at functionality to open array at the specific timestamp (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetArrayMetadata", {
  # tests for GetArrayMetadata
  # base path: http://localhost/v1
  # get metadata on an array
  # @param namespace character namespace array is in (an organization name or user's username)
  # @param array character name/uri of array that is url-encoded
  # @return [ArrayInfo]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetArrayMetadataCapnp", {
  # tests for GetArrayMetadataCapnp
  # base path: http://localhost/v1
  # get metadata on an array
  # @param namespace character namespace array is in (an organization name or user's username)
  # @param array character name/uri of array that is url-encoded
  # @return [ArrayMetadata]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetArrayNonEmptyDomain", {
  # tests for GetArrayNonEmptyDomain
  # base path: http://localhost/v1
  # get the non empty domain of an array
  # @param namespace character namespace array is in (an organization name or user's username)
  # @param array character name/uri of array that is url-encoded
  # @param content.type character Content Type of input and return mime
  # @param x.payer character Name of organization or user who should be charged for this request (optional)
  # @return [NonEmptyDomain]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetArrayNonEmptyDomainJson", {
  # tests for GetArrayNonEmptyDomainJson
  # base path: http://localhost/v1
  # get non-empty domain from the array in json format
  # @param namespace character namespace array is in (an organization name or user's username)
  # @param array character name/uri of array that is url-encoded
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetArraySampleData", {
  # tests for GetArraySampleData
  # base path: http://localhost/v1
  # get an sample set of data from the array
  # @param namespace character namespace array is in (an organization name or user's username)
  # @param array character name/uri of array that is url-encoded
  # @param samples numeric Number of sample results to return (optional)
  # @return [ArraySample]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetArraySharingPolicies", {
  # tests for GetArraySharingPolicies
  # base path: http://localhost/v1
  # Get all sharing details of the array
  # @param namespace character namespace array is in (an organization name or user's username)
  # @param array character name/uri of array that is url-encoded
  # @return [array[ArraySharing]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetArraysInNamespace", {
  # tests for GetArraysInNamespace
  # base path: http://localhost/v1
  # get metadata on all arrays in a namespace
  # @param namespace character namespace array is in (an organization name or user's username)
  # @return [array[ArrayInfo]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetFragmentEndTimestamp", {
  # tests for GetFragmentEndTimestamp
  # base path: http://localhost/v1
  # Get fragment end_timestamp on an array, will search for the closest end_timestamp to the timestamp asked
  # @param namespace character namespace array is in (an organization name or user's username)
  # @param array character name/uri of array that is url-encoded
  # @param end.timestamp integer Milliseconds since Unix epoch (optional)
  # @return [integer]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetLastAccessedArrays", {
  # tests for GetLastAccessedArrays
  # base path: http://localhost/v1
  # @return [array[LastAccessedArray]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RegisterArray", {
  # tests for RegisterArray
  # base path: http://localhost/v1
  # register an array at a specified URI registered to the given namespace
  # @param namespace character namespace array is in (an organization name or user's username)
  # @param array character name/uri of array that is url-encoded
  # @param array.metadata ArrayInfoUpdate metadata associated with array
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ShareArray", {
  # tests for ShareArray
  # base path: http://localhost/v1
  # Share an array with a user
  # @param namespace character namespace array is in (an organization name or user's username)
  # @param array character name/uri of array that is url-encoded
  # @param array.sharing ArraySharing Namespace and list of permissions to share with. An empty list of permissions will remove the namespace, if permissions already exist they will be deleted then new ones added. In the event of a failure, the new polcies will be rolled back to prevent partial policies, and its likely the array will not be shared with the namespace at all
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateArrayMetadata", {
  # tests for UpdateArrayMetadata
  # base path: http://localhost/v1
  # update metadata on an array
  # @param namespace character namespace array is in (an organization name or user's username)
  # @param array character name/uri of array that is url-encoded
  # @param array.metadata ArrayInfoUpdate array metadata to update
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateArrayMetadataCapnp", {
  # tests for UpdateArrayMetadataCapnp
  # base path: http://localhost/v1
  # update metadata on an array
  # @param namespace character namespace array is in (an organization name or user's username)
  # @param array character name/uri of array that is url-encoded
  # @param array.metadata.entries ArrayMetadata List of metadata entries
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("VacuumArray", {
  # tests for VacuumArray
  # base path: http://localhost/v1
  # vacuum an array at a specified URI
  # @param namespace character namespace array is in (an organization name or user's username)
  # @param array character name/uri of array that is url-encoded
  # @param tiledb.config TileDBConfig tiledb configuration
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

