# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ArraySchema")

model.instance <- ArraySchema$new()

test_that("uri", {
  # tests for the property `uri` (character)
  # URI of schema

  # uncomment below to test the property 
  #expect_equal(model.instance$`uri`, "EXPECTED_RESULT")
})

test_that("version", {
  # tests for the property `version` (array[integer])
  # file format version

  # uncomment below to test the property 
  #expect_equal(model.instance$`version`, "EXPECTED_RESULT")
})

test_that("arrayType", {
  # tests for the property `arrayType` (ArrayType)

  # uncomment below to test the property 
  #expect_equal(model.instance$`arrayType`, "EXPECTED_RESULT")
})

test_that("tileOrder", {
  # tests for the property `tileOrder` (Layout)

  # uncomment below to test the property 
  #expect_equal(model.instance$`tileOrder`, "EXPECTED_RESULT")
})

test_that("cellOrder", {
  # tests for the property `cellOrder` (Layout)

  # uncomment below to test the property 
  #expect_equal(model.instance$`cellOrder`, "EXPECTED_RESULT")
})

test_that("capacity", {
  # tests for the property `capacity` (integer)
  # Capacity of array

  # uncomment below to test the property 
  #expect_equal(model.instance$`capacity`, "EXPECTED_RESULT")
})

test_that("coordsFilterPipeline", {
  # tests for the property `coordsFilterPipeline` (FilterPipeline)

  # uncomment below to test the property 
  #expect_equal(model.instance$`coordsFilterPipeline`, "EXPECTED_RESULT")
})

test_that("offsetFilterPipeline", {
  # tests for the property `offsetFilterPipeline` (FilterPipeline)

  # uncomment below to test the property 
  #expect_equal(model.instance$`offsetFilterPipeline`, "EXPECTED_RESULT")
})

test_that("domain", {
  # tests for the property `domain` (Domain)

  # uncomment below to test the property 
  #expect_equal(model.instance$`domain`, "EXPECTED_RESULT")
})

test_that("attributes", {
  # tests for the property `attributes` (array[Attribute])
  # Attributes of array

  # uncomment below to test the property 
  #expect_equal(model.instance$`attributes`, "EXPECTED_RESULT")
})

test_that("allowsDuplicates", {
  # tests for the property `allowsDuplicates` (character)
  # True if the array allows coordinate duplicates. Applicable only to sparse arrays.

  # uncomment below to test the property 
  #expect_equal(model.instance$`allowsDuplicates`, "EXPECTED_RESULT")
})

