# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test NotebookFavoritesData")

model.instance <- NotebookFavoritesData$new()

test_that("notebooks", {
  # tests for the property `notebooks` (array[ArrayInfo])
  # List of notebook infos

  # uncomment below to test the property 
  #expect_equal(model.instance$`notebooks`, "EXPECTED_RESULT")
})

test_that("pagination_metadata", {
  # tests for the property `pagination_metadata` (PaginationMetadata)

  # uncomment below to test the property 
  #expect_equal(model.instance$`pagination_metadata`, "EXPECTED_RESULT")
})

