# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Subarray")

model.instance <- Subarray$new()

test_that("layout", {
  # tests for the property `layout` (Layout)

  # uncomment below to test the property 
  #expect_equal(model.instance$`layout`, "EXPECTED_RESULT")
})

test_that("ranges", {
  # tests for the property `ranges` (array[SubarrayRanges])
  # List of 1D ranges, one per dimension

  # uncomment below to test the property 
  #expect_equal(model.instance$`ranges`, "EXPECTED_RESULT")
})

