# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse200")

model.instance <- InlineResponse200$new()

test_that("stats", {
  # tests for the property `stats` (character)
  # string of stats from tiledb

  # uncomment below to test the property 
  #expect_equal(model.instance$`stats`, "EXPECTED_RESULT")
})

