# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UDFFavorite")

model.instance <- UDFFavorite$new()

test_that("id", {
  # tests for the property `id` (character)
  # unique uuid of the favorite

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("created_at", {
  # tests for the property `created_at` (character)
  # Datetime the favorite was created in UTC

  # uncomment below to test the property 
  #expect_equal(model.instance$`created_at`, "EXPECTED_RESULT")
})

test_that("udf_uuid", {
  # tests for the property `udf_uuid` (character)
  # unique uuid of the UDF

  # uncomment below to test the property 
  #expect_equal(model.instance$`udf_uuid`, "EXPECTED_RESULT")
})

