# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test NotebookFavorite")

model.instance <- NotebookFavorite$new()

test_that("id", {
  # tests for the property `id` (character)
  # unique uuid of the favorite

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("created_at", {
  # tests for the property `created_at` (character)
  # Datetime the favorite was created in UTC

  # uncomment below to test the property 
  #expect_equal(model.instance$`created_at`, "EXPECTED_RESULT")
})

test_that("notebook_uuid", {
  # tests for the property `notebook_uuid` (character)
  # unique uuid of the notebook

  # uncomment below to test the property 
  #expect_equal(model.instance$`notebook_uuid`, "EXPECTED_RESULT")
})

