# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Attribute")

model.instance <- Attribute$new()

test_that("name", {
  # tests for the property `name` (character)
  # Attribute name

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (Datatype)

  # uncomment below to test the property 
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("filterPipeline", {
  # tests for the property `filterPipeline` (FilterPipeline)

  # uncomment below to test the property 
  #expect_equal(model.instance$`filterPipeline`, "EXPECTED_RESULT")
})

test_that("cellValNum", {
  # tests for the property `cellValNum` (integer)
  # Attribute number of values per cell

  # uncomment below to test the property 
  #expect_equal(model.instance$`cellValNum`, "EXPECTED_RESULT")
})

