# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Dimension")

model.instance <- Dimension$new()

test_that("name", {
  # tests for the property `name` (character)
  # Dimension name

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (Datatype)

  # uncomment below to test the property 
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("domain", {
  # tests for the property `domain` (DomainArray)

  # uncomment below to test the property 
  #expect_equal(model.instance$`domain`, "EXPECTED_RESULT")
})

test_that("nullTileExtent", {
  # tests for the property `nullTileExtent` (character)
  # Is tile extent null

  # uncomment below to test the property 
  #expect_equal(model.instance$`nullTileExtent`, "EXPECTED_RESULT")
})

test_that("tileExtent", {
  # tests for the property `tileExtent` (DimensionTileExtent)

  # uncomment below to test the property 
  #expect_equal(model.instance$`tileExtent`, "EXPECTED_RESULT")
})

test_that("filterPipeline", {
  # tests for the property `filterPipeline` (FilterPipeline)

  # uncomment below to test the property 
  #expect_equal(model.instance$`filterPipeline`, "EXPECTED_RESULT")
})

