# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UDFRanges")

model.instance <- UDFRanges$new()

test_that("layout", {
  # tests for the property `layout` (Layout)

  # uncomment below to test the property 
  #expect_equal(model.instance$`layout`, "EXPECTED_RESULT")
})

test_that("ranges", {
  # tests for the property `ranges` (array[array[numeric]])
  # List of ranges,

  # uncomment below to test the property 
  #expect_equal(model.instance$`ranges`, "EXPECTED_RESULT")
})

