# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UDFSharing")

model.instance <- UDFSharing$new()

test_that("actions", {
  # tests for the property `actions` (array[UDFActions])
  # List of permitted actions

  # uncomment below to test the property 
  #expect_equal(model.instance$`actions`, "EXPECTED_RESULT")
})

test_that("namespace", {
  # tests for the property `namespace` (character)
  # namespace being granted array access can be a user or organization

  # uncomment below to test the property 
  #expect_equal(model.instance$`namespace`, "EXPECTED_RESULT")
})

test_that("namespace_type", {
  # tests for the property `namespace_type` (character)
  # details on if the namespace is a organization or user

  # uncomment below to test the property 
  #expect_equal(model.instance$`namespace_type`, "EXPECTED_RESULT")
})

