# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test QueryReader")

model.instance <- QueryReader$new()

test_that("layout", {
  # tests for the property `layout` (Layout)

  # uncomment below to test the property 
  #expect_equal(model.instance$`layout`, "EXPECTED_RESULT")
})

test_that("subarray", {
  # tests for the property `subarray` (Subarray)

  # uncomment below to test the property 
  #expect_equal(model.instance$`subarray`, "EXPECTED_RESULT")
})

test_that("readState", {
  # tests for the property `readState` (ReadState)

  # uncomment below to test the property 
  #expect_equal(model.instance$`readState`, "EXPECTED_RESULT")
})

test_that("varOffsetsMode", {
  # tests for the property `varOffsetsMode` (character)
  # The offsets format (bytes or elements) to be used.

  # uncomment below to test the property 
  #expect_equal(model.instance$`varOffsetsMode`, "EXPECTED_RESULT")
})

test_that("varOffsetsAddExtraElement", {
  # tests for the property `varOffsetsAddExtraElement` (character)
  # True if an extra element will be added to the end of the offsets buffer.

  # uncomment below to test the property 
  #expect_equal(model.instance$`varOffsetsAddExtraElement`, "EXPECTED_RESULT")
})

test_that("varOffsetsBitsize", {
  # tests for the property `varOffsetsBitsize` (integer)
  # The offsets bitsize (32 or 64) to be used.

  # uncomment below to test the property 
  #expect_equal(model.instance$`varOffsetsBitsize`, "EXPECTED_RESULT")
})

