# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Array")

model.instance <- Array$new()

test_that("timestamp", {
  # tests for the property `timestamp` (numeric)
  # timestamp (epoch milliseconds) array is opened at

  # uncomment below to test the property 
  #expect_equal(model.instance$`timestamp`, "EXPECTED_RESULT")
})

test_that("queryType", {
  # tests for the property `queryType` (Querytype)

  # uncomment below to test the property 
  #expect_equal(model.instance$`queryType`, "EXPECTED_RESULT")
})

test_that("uri", {
  # tests for the property `uri` (character)
  # Array uri

  # uncomment below to test the property 
  #expect_equal(model.instance$`uri`, "EXPECTED_RESULT")
})

