# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UserApi")

api.instance <- UserApi$new()

test_that("AddAWSAccessCredentials", {
  # tests for AddAWSAccessCredentials
  # base path: http://localhost/v1
  # Add aws keys
  # @param namespace character namespace
  # @param aws.access.credentials AWSAccessCredentials aws access credentials to store for a namespace
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("AddUserToOrganization", {
  # tests for AddUserToOrganization
  # base path: http://localhost/v1
  # add a user to an organization
  # @param organization character organization name
  # @param user OrganizationUser user to add
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CheckAWSAccessCredentials", {
  # tests for CheckAWSAccessCredentials
  # base path: http://localhost/v1
  # Check if aws keys are set
  # @param namespace character namespace
  # @return [array[AWSAccessCredentials]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CheckAWSAccessCredentialsByName", {
  # tests for CheckAWSAccessCredentialsByName
  # base path: http://localhost/v1
  # Check if aws keys are set by name
  # @param namespace character namespace
  # @param name character name
  # @return [AWSAccessCredentials]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ConfirmEmail", {
  # tests for ConfirmEmail
  # base path: http://localhost/v1
  # confirm user email
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CreateUser", {
  # tests for CreateUser
  # base path: http://localhost/v1
  # create a user
  # @param user User user to create
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteAWSAccessCredentials", {
  # tests for DeleteAWSAccessCredentials
  # base path: http://localhost/v1
  # delete a AWS Access credentials in a namespace. This will likely cause arrays to become unreachable
  # @param namespace character namespace
  # @param name character name
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteUser", {
  # tests for DeleteUser
  # base path: http://localhost/v1
  # delete a user
  # @param username character username or id
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteUserFromOrganization", {
  # tests for DeleteUserFromOrganization
  # base path: http://localhost/v1
  # delete a user from an organization
  # @param organization character organization name
  # @param username character username to manipulate
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetOrganizationUser", {
  # tests for GetOrganizationUser
  # base path: http://localhost/v1
  # get a user from an organization
  # @param organization character organization name
  # @param username character username to manipulate
  # @return [OrganizationUser]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetSession", {
  # tests for GetSession
  # base path: http://localhost/v1
  # Get session token for user
  # @param remember.me character flag to create a token with expiration of 30 days, default is false (optional)
  # @return [Token]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetTokenScopes", {
  # tests for GetTokenScopes
  # base path: http://localhost/v1
  # retrieves available token scopes for a user
  # @return [array[TokenScope]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetUser", {
  # tests for GetUser
  # base path: http://localhost/v1
  # get a user
  # @return [User]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetUserWithUsername", {
  # tests for GetUserWithUsername
  # base path: http://localhost/v1
  # get a user
  # @param username character username or id
  # @return [User]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RequestToken", {
  # tests for RequestToken
  # base path: http://localhost/v1
  # Request an authorization token, optionally taken a TokenRequest object to set parameters on the token
  # @param token.request TokenRequest token request object (optional)
  # @return [Token]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ResetUserPassword", {
  # tests for ResetUserPassword
  # base path: http://localhost/v1
  # reset user password
  # @param user InlineObject 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RevokeToken", {
  # tests for RevokeToken
  # base path: http://localhost/v1
  # revoke an authorization token
  # @param token character token name or token itself
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("TokensGet", {
  # tests for TokensGet
  # base path: http://localhost/v1
  # Fetch a list of user tokens
  # @return [array[Token]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("TokensSessionGet", {
  # tests for TokensSessionGet
  # base path: http://localhost/v1
  # Fetch a list of user session tokens
  # @return [array[Token]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateAWSAccessCredentials", {
  # tests for UpdateAWSAccessCredentials
  # base path: http://localhost/v1
  # Update aws keys or associated buckets. This will update the key associations for each array in the namespace
  # @param namespace character namespace
  # @param name character name
  # @param aws.access.credentials AWSAccessCredentials aws credentials to update
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateUser", {
  # tests for UpdateUser
  # base path: http://localhost/v1
  # update a user
  # @param username character username or id
  # @param user User user details to update
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateUserInOrganization", {
  # tests for UpdateUserInOrganization
  # base path: http://localhost/v1
  # update a user in an organization
  # @param organization character organization name
  # @param username character username to manipulate
  # @param user OrganizationUser user details to update
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

