# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test NotebooksApi")

api.instance <- NotebooksApi$new()

test_that("NotebooksNamespaceArrayEndTimestampsGet", {
  # tests for NotebooksNamespaceArrayEndTimestampsGet
  # base path: http://localhost/v1
  # retrieve a list of timestamps from the array fragment info listing in milliseconds, paginated
  # @param namespace character namespace array is in (an organization name or user's username)
  # @param array character name/uri of array that is url-encoded
  # @param page integer pagination offset (optional)
  # @param per.page integer pagination limit (optional)
  # @return [ArrayEndTimestampData]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

