# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ArrayFavorite")

model.instance <- ArrayFavorite$new()

test_that("id", {
  # tests for the property `id` (character)
  # unique uuid of the favorite

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("created_at", {
  # tests for the property `created_at` (character)
  # Datetime the favorite was created in UTC

  # uncomment below to test the property 
  #expect_equal(model.instance$`created_at`, "EXPECTED_RESULT")
})

test_that("array_uuid", {
  # tests for the property `array_uuid` (character)
  # unique uuid of the array

  # uncomment below to test the property 
  #expect_equal(model.instance$`array_uuid`, "EXPECTED_RESULT")
})

