# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test NotebookSettings")

model.instance <- NotebookSettings$new()

test_that("default_s3_path", {
  # tests for the property `default_s3_path` (character)
  # default s3 path to store newly created notebooks

  # uncomment below to test the property 
  #expect_equal(model.instance$`default_s3_path`, "EXPECTED_RESULT")
})

