# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SubarrayPartitionerState")

model.instance <- SubarrayPartitionerState$new()

test_that("start", {
  # tests for the property `start` (integer)
  # State start

  # uncomment below to test the property 
  #expect_equal(model.instance$`start`, "EXPECTED_RESULT")
})

test_that("end", {
  # tests for the property `end` (integer)
  # State end

  # uncomment below to test the property 
  #expect_equal(model.instance$`end`, "EXPECTED_RESULT")
})

test_that("singleRange", {
  # tests for the property `singleRange` (array[Subarray])
  # State singleRange

  # uncomment below to test the property 
  #expect_equal(model.instance$`singleRange`, "EXPECTED_RESULT")
})

test_that("multiRange", {
  # tests for the property `multiRange` (array[Subarray])
  # State multiRange

  # uncomment below to test the property 
  #expect_equal(model.instance$`multiRange`, "EXPECTED_RESULT")
})

