# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UDFInfoUpdate")

model.instance <- UDFInfoUpdate$new()

test_that("name", {
  # tests for the property `name` (character)
  # name of udf

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("language", {
  # tests for the property `language` (UDFLanguage)

  # uncomment below to test the property 
  #expect_equal(model.instance$`language`, "EXPECTED_RESULT")
})

test_that("version", {
  # tests for the property `version` (character)
  # Type-specific version

  # uncomment below to test the property 
  #expect_equal(model.instance$`version`, "EXPECTED_RESULT")
})

test_that("image_name", {
  # tests for the property `image_name` (character)
  # Docker image name to use for udf

  # uncomment below to test the property 
  #expect_equal(model.instance$`image_name`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (UDFType)

  # uncomment below to test the property 
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("exec", {
  # tests for the property `exec` (character)
  # Type-specific executable text

  # uncomment below to test the property 
  #expect_equal(model.instance$`exec`, "EXPECTED_RESULT")
})

test_that("exec_raw", {
  # tests for the property `exec_raw` (character)
  # optional raw text to store of serialized function, used for showing in UI

  # uncomment below to test the property 
  #expect_equal(model.instance$`exec_raw`, "EXPECTED_RESULT")
})

test_that("readme", {
  # tests for the property `readme` (character)
  # Markdown readme of udfs

  # uncomment below to test the property 
  #expect_equal(model.instance$`readme`, "EXPECTED_RESULT")
})

test_that("license_id", {
  # tests for the property `license_id` (character)
  # License identifier from SPDX License List or Custom

  # uncomment below to test the property 
  #expect_equal(model.instance$`license_id`, "EXPECTED_RESULT")
})

test_that("license_text", {
  # tests for the property `license_text` (character)
  # License text

  # uncomment below to test the property 
  #expect_equal(model.instance$`license_text`, "EXPECTED_RESULT")
})

test_that("tags", {
  # tests for the property `tags` (array[character])
  # optional tags for udf

  # uncomment below to test the property 
  #expect_equal(model.instance$`tags`, "EXPECTED_RESULT")
})

