# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UDFListingData")

model.instance <- UDFListingData$new()

test_that("udf_info_list", {
  # tests for the property `udf_info_list` (array[UDFInfo])
  # List of UDFInfo

  # uncomment below to test the property 
  #expect_equal(model.instance$`udf_info_list`, "EXPECTED_RESULT")
})

test_that("pagination_metadata", {
  # tests for the property `pagination_metadata` (PaginationMetadata)

  # uncomment below to test the property 
  #expect_equal(model.instance$`pagination_metadata`, "EXPECTED_RESULT")
})

