# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ArrayEndTimestampData")

model.instance <- ArrayEndTimestampData$new()

test_that("end_timestamps", {
  # tests for the property `end_timestamps` (array[integer])
  # List of timestamps expressed in milliseconds since Unix epoch

  # uncomment below to test the property 
  #expect_equal(model.instance$`end_timestamps`, "EXPECTED_RESULT")
})

test_that("pagination_metadata", {
  # tests for the property `pagination_metadata` (PaginationMetadata)

  # uncomment below to test the property 
  #expect_equal(model.instance$`pagination_metadata`, "EXPECTED_RESULT")
})

