# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineObject")

model.instance <- InlineObject$new()

test_that("password", {
  # tests for the property `password` (character)
  # password

  # uncomment below to test the property 
  #expect_equal(model.instance$`password`, "EXPECTED_RESULT")
})

