# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test QueryJson")

model.instance <- QueryJson$new()

test_that("query_ranges", {
  # tests for the property `query_ranges` (QueryRanges)

  # uncomment below to test the property 
  #expect_equal(model.instance$`query_ranges`, "EXPECTED_RESULT")
})

test_that("fields", {
  # tests for the property `fields` (array[character])
  # List of fields to return data from, empty means return data for all fields

  # uncomment below to test the property 
  #expect_equal(model.instance$`fields`, "EXPECTED_RESULT")
})

