# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrganizationApi")

api.instance <- OrganizationApi$new()

test_that("AddAWSAccessCredentials", {
  # tests for AddAWSAccessCredentials
  # base path: http://localhost/v1
  # Add aws keys
  # @param namespace character namespace
  # @param aws.access.credentials AWSAccessCredentials aws access credentials to store for a namespace
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("AddUserToOrganization", {
  # tests for AddUserToOrganization
  # base path: http://localhost/v1
  # add a user to an organization
  # @param organization character organization name
  # @param user OrganizationUser user to add
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CheckAWSAccessCredentials", {
  # tests for CheckAWSAccessCredentials
  # base path: http://localhost/v1
  # Check if aws keys are set
  # @param namespace character namespace
  # @return [array[AWSAccessCredentials]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CheckAWSAccessCredentialsByName", {
  # tests for CheckAWSAccessCredentialsByName
  # base path: http://localhost/v1
  # Check if aws keys are set by name
  # @param namespace character namespace
  # @param name character name
  # @return [AWSAccessCredentials]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CreateOrganization", {
  # tests for CreateOrganization
  # base path: http://localhost/v1
  # create a organization, the user creating will be listed as owner
  # @param organization Organization organization to create
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteAWSAccessCredentials", {
  # tests for DeleteAWSAccessCredentials
  # base path: http://localhost/v1
  # delete a AWS Access credentials in a namespace. This will likely cause arrays to become unreachable
  # @param namespace character namespace
  # @param name character name
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteOrganization", {
  # tests for DeleteOrganization
  # base path: http://localhost/v1
  # delete a organization
  # @param organization character organization name or id
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteUserFromOrganization", {
  # tests for DeleteUserFromOrganization
  # base path: http://localhost/v1
  # delete a user from an organization
  # @param organization character organization name
  # @param username character username to manipulate
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetAllOrganizations", {
  # tests for GetAllOrganizations
  # base path: http://localhost/v1
  # get all organizations that the user is member of
  # @return [array[Organization]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetOrganization", {
  # tests for GetOrganization
  # base path: http://localhost/v1
  # get a organization
  # @param organization character organization name or id
  # @return [Organization]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetOrganizationUser", {
  # tests for GetOrganizationUser
  # base path: http://localhost/v1
  # get a user from an organization
  # @param organization character organization name
  # @param username character username to manipulate
  # @return [OrganizationUser]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateAWSAccessCredentials", {
  # tests for UpdateAWSAccessCredentials
  # base path: http://localhost/v1
  # Update aws keys or associated buckets. This will update the key associations for each array in the namespace
  # @param namespace character namespace
  # @param name character name
  # @param aws.access.credentials AWSAccessCredentials aws credentials to update
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateOrganization", {
  # tests for UpdateOrganization
  # base path: http://localhost/v1
  # update a organization
  # @param organization character organization name or id
  # @param organization.details Organization organization details to update
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateUserInOrganization", {
  # tests for UpdateUserInOrganization
  # base path: http://localhost/v1
  # update a user in an organization
  # @param organization character organization name
  # @param username character username to manipulate
  # @param user OrganizationUser user details to update
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

