# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ArrayFavoritesData")

model.instance <- ArrayFavoritesData$new()

test_that("arrays", {
  # tests for the property `arrays` (array[ArrayInfo])
  # List of array infos

  # uncomment below to test the property 
  #expect_equal(model.instance$`arrays`, "EXPECTED_RESULT")
})

test_that("pagination_metadata", {
  # tests for the property `pagination_metadata` (PaginationMetadata)

  # uncomment below to test the property 
  #expect_equal(model.instance$`pagination_metadata`, "EXPECTED_RESULT")
})

