# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TasksApi")

api.instance <- TasksApi$new()

test_that("RunSQL", {
  # tests for RunSQL
  # base path: http://localhost/v1
  # Run a sql query
  # @param namespace character namespace to run task under is in (an organization name or user's username)
  # @param sql SQLParameters sql being submitted
  # @param accept.encoding character Encoding to use (optional)
  # @return [array[object]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("TaskIdGet", {
  # tests for TaskIdGet
  # base path: http://localhost/v1
  # Fetch an array task
  # @param id character task id to fetch
  # @return [ArrayTask]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("TasksGet", {
  # tests for TasksGet
  # base path: http://localhost/v1
  # Fetch a list of all array tasks a user has access to
  # @param namespace character namespace to filter (optional)
  # @param created.by character username to filter (optional)
  # @param array character name/uri of array that is url-encoded to filter (optional)
  # @param start integer start time for tasks to filter by (optional)
  # @param end integer end time for tasks to filter by (optional)
  # @param page integer pagination offset (optional)
  # @param per.page integer pagination limit (optional)
  # @param type character task type, \"QUERY\", \"SQL\", \"UDF\" (optional)
  # @param status character Filter to only return these statuses (optional)
  # @param search character search string that will look at name, namespace or description fields (optional)
  # @param orderby character sort by which field valid values include start_time, name (optional)
  # @return [ArrayTaskData]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

