# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MLModelFavoritesData")

model.instance <- MLModelFavoritesData$new()

test_that("mlmodels", {
  # tests for the property `mlmodels` (array[ArrayInfo])
  # List of MLModel infos

  # uncomment below to test the property 
  #expect_equal(model.instance$`mlmodels`, "EXPECTED_RESULT")
})

test_that("pagination_metadata", {
  # tests for the property `pagination_metadata` (PaginationMetadata)

  # uncomment below to test the property 
  #expect_equal(model.instance$`pagination_metadata`, "EXPECTED_RESULT")
})

