# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ArrayMetadataEntry")

model.instance <- ArrayMetadataEntry$new()

test_that("key", {
  # tests for the property `key` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`key`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("value_num", {
  # tests for the property `value_num` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`value_num`, "EXPECTED_RESULT")
})

test_that("value", {
  # tests for the property `value` (array[integer])

  # uncomment below to test the property 
  #expect_equal(model.instance$`value`, "EXPECTED_RESULT")
})

test_that("del", {
  # tests for the property `del` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`del`, "EXPECTED_RESULT")
})

