# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MLModelFavorite")

model.instance <- MLModelFavorite$new()

test_that("id", {
  # tests for the property `id` (character)
  # unique uuid of the favorite

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("created_at", {
  # tests for the property `created_at` (character)
  # Datetime the favorite was created in UTC

  # uncomment below to test the property 
  #expect_equal(model.instance$`created_at`, "EXPECTED_RESULT")
})

test_that("mlmodel_uuid", {
  # tests for the property `mlmodel_uuid` (character)
  # unique uuid of the MLModel

  # uncomment below to test the property 
  #expect_equal(model.instance$`mlmodel_uuid`, "EXPECTED_RESULT")
})

