# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TileDBConfig")

model.instance <- TileDBConfig$new()

test_that("configs", {
  # tests for the property `configs` (map(character))

  # uncomment below to test the property 
  #expect_equal(model.instance$`configs`, "EXPECTED_RESULT")
})

