# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test User")

model.instance <- User$new()

test_that("id", {
  # tests for the property `id` (character)
  # unique id of user

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("username", {
  # tests for the property `username` (character)
  # username must be unique

  # uncomment below to test the property 
  #expect_equal(model.instance$`username`, "EXPECTED_RESULT")
})

test_that("password", {
  # tests for the property `password` (character)
  # password

  # uncomment below to test the property 
  #expect_equal(model.instance$`password`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # the user&#39;s full, real name

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("email", {
  # tests for the property `email` (character)
  # the user&#39;s email

  # uncomment below to test the property 
  #expect_equal(model.instance$`email`, "EXPECTED_RESULT")
})

test_that("is_valid_email", {
  # tests for the property `is_valid_email` (character)
  # user&#39;s email is validated to be correct

  # uncomment below to test the property 
  #expect_equal(model.instance$`is_valid_email`, "EXPECTED_RESULT")
})

test_that("stripe_connect", {
  # tests for the property `stripe_connect` (character)
  # Denotes that the user is able to apply pricing to arrays by means of Stripe Connect

  # uncomment below to test the property 
  #expect_equal(model.instance$`stripe_connect`, "EXPECTED_RESULT")
})

test_that("company", {
  # tests for the property `company` (character)
  # the user&#39;s company

  # uncomment below to test the property 
  #expect_equal(model.instance$`company`, "EXPECTED_RESULT")
})

test_that("logo", {
  # tests for the property `logo` (character)
  # the user&#39;s logo

  # uncomment below to test the property 
  #expect_equal(model.instance$`logo`, "EXPECTED_RESULT")
})

test_that("last_activity_date", {
  # tests for the property `last_activity_date` (character)
  # when the user last logged in (set by the server)

  # uncomment below to test the property 
  #expect_equal(model.instance$`last_activity_date`, "EXPECTED_RESULT")
})

test_that("timezone", {
  # tests for the property `timezone` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`timezone`, "EXPECTED_RESULT")
})

test_that("organizations", {
  # tests for the property `organizations` (array[OrganizationUser])
  # Array of organizations a user is part of and their roles

  # uncomment below to test the property 
  #expect_equal(model.instance$`organizations`, "EXPECTED_RESULT")
})

test_that("allowed_actions", {
  # tests for the property `allowed_actions` (array[NamespaceActions])
  # list of actions user is allowed to do on this organization

  # uncomment below to test the property 
  #expect_equal(model.instance$`allowed_actions`, "EXPECTED_RESULT")
})

test_that("enabled_features", {
  # tests for the property `enabled_features` (array[character])
  # List of extra/optional/beta features to enable for namespace

  # uncomment below to test the property 
  #expect_equal(model.instance$`enabled_features`, "EXPECTED_RESULT")
})

test_that("unpaid_subscription", {
  # tests for the property `unpaid_subscription` (character)
  # A notice that the user has an unpaid subscription

  # uncomment below to test the property 
  #expect_equal(model.instance$`unpaid_subscription`, "EXPECTED_RESULT")
})

test_that("default_s3_path", {
  # tests for the property `default_s3_path` (character)
  # default s3 path to store newly created notebooks

  # uncomment below to test the property 
  #expect_equal(model.instance$`default_s3_path`, "EXPECTED_RESULT")
})

test_that("default_s3_path_credentials_name", {
  # tests for the property `default_s3_path_credentials_name` (character)
  # Default s3 path credentials name is the credentials name to use along with default_s3_path

  # uncomment below to test the property 
  #expect_equal(model.instance$`default_s3_path_credentials_name`, "EXPECTED_RESULT")
})

test_that("default_namespace_charged", {
  # tests for the property `default_namespace_charged` (character)
  # Override the default namespace charged for actions when no namespace is specified

  # uncomment below to test the property 
  #expect_equal(model.instance$`default_namespace_charged`, "EXPECTED_RESULT")
})

