# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UDFFavoritesData")

model.instance <- UDFFavoritesData$new()

test_that("udfs", {
  # tests for the property `udfs` (array[ArrayInfo])
  # List of UDF infos

  # uncomment below to test the property 
  #expect_equal(model.instance$`udfs`, "EXPECTED_RESULT")
})

test_that("pagination_metadata", {
  # tests for the property `pagination_metadata` (PaginationMetadata)

  # uncomment below to test the property 
  #expect_equal(model.instance$`pagination_metadata`, "EXPECTED_RESULT")
})

