# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SubarrayPartitionerCurrent")

model.instance <- SubarrayPartitionerCurrent$new()

test_that("subarray", {
  # tests for the property `subarray` (Subarray)

  # uncomment below to test the property 
  #expect_equal(model.instance$`subarray`, "EXPECTED_RESULT")
})

test_that("start", {
  # tests for the property `start` (integer)
  # PartitionInfo start

  # uncomment below to test the property 
  #expect_equal(model.instance$`start`, "EXPECTED_RESULT")
})

test_that("end", {
  # tests for the property `end` (integer)
  # PartitionInfo end

  # uncomment below to test the property 
  #expect_equal(model.instance$`end`, "EXPECTED_RESULT")
})

test_that("splitMultiRange", {
  # tests for the property `splitMultiRange` (character)
  # PartitionInfo splitMultiRange

  # uncomment below to test the property 
  #expect_equal(model.instance$`splitMultiRange`, "EXPECTED_RESULT")
})

