# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test NotebookStatus")

model.instance <- NotebookStatus$new()

test_that("namespace", {
  # tests for the property `namespace` (character)
  # namespace of notebook

  # uncomment below to test the property 
  #expect_equal(model.instance$`namespace`, "EXPECTED_RESULT")
})

test_that("uptime", {
  # tests for the property `uptime` (integer)
  # duration notebook has been running in seconds

  # uncomment below to test the property 
  #expect_equal(model.instance$`uptime`, "EXPECTED_RESULT")
})

test_that("cpu_usage", {
  # tests for the property `cpu_usage` (integer)
  # current cpu usage in millicpu

  # uncomment below to test the property 
  #expect_equal(model.instance$`cpu_usage`, "EXPECTED_RESULT")
})

test_that("memory_usage", {
  # tests for the property `memory_usage` (integer)
  # memory usage in bytes

  # uncomment below to test the property 
  #expect_equal(model.instance$`memory_usage`, "EXPECTED_RESULT")
})

test_that("memory_limit", {
  # tests for the property `memory_limit` (integer)
  # memory allocated to notebook server in bytes

  # uncomment below to test the property 
  #expect_equal(model.instance$`memory_limit`, "EXPECTED_RESULT")
})

test_that("cpu_count", {
  # tests for the property `cpu_count` (integer)
  # millicpu allocated to notebook server

  # uncomment below to test the property 
  #expect_equal(model.instance$`cpu_count`, "EXPECTED_RESULT")
})

