# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test QueryReader")

model.instance <- QueryReader$new()

test_that("layout", {
  # tests for the property `layout` (Layout)

  # uncomment below to test the property 
  #expect_equal(model.instance$`layout`, "EXPECTED_RESULT")
})

test_that("subarray", {
  # tests for the property `subarray` (Subarray)

  # uncomment below to test the property 
  #expect_equal(model.instance$`subarray`, "EXPECTED_RESULT")
})

test_that("readState", {
  # tests for the property `readState` (ReadState)

  # uncomment below to test the property 
  #expect_equal(model.instance$`readState`, "EXPECTED_RESULT")
})

