# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AttributeBufferSize")

model.instance <- AttributeBufferSize$new()

test_that("attribute", {
  # tests for the property `attribute` (character)
  # name of attribute

  # uncomment below to test the property 
  #expect_equal(model.instance$`attribute`, "EXPECTED_RESULT")
})

test_that("offsetBytes", {
  # tests for the property `offsetBytes` (integer)
  # buffer size (in bytes) of offset buffer

  # uncomment below to test the property 
  #expect_equal(model.instance$`offsetBytes`, "EXPECTED_RESULT")
})

test_that("dataBytes", {
  # tests for the property `dataBytes` (integer)
  # buffer size (in bytes) of data buffer

  # uncomment below to test the property 
  #expect_equal(model.instance$`dataBytes`, "EXPECTED_RESULT")
})

