# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test NotebookApi")

api.instance <- NotebookApi$new()

test_that("GetNotebookServerStatus", {
  # tests for GetNotebookServerStatus
  # base path: http://localhost/v1
  # Get status of the notebook server
  # @param namespace character namespace notebook is in (an organization name or user's username)
  # @return [NotebookStatus]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ShutdownNotebookServer", {
  # tests for ShutdownNotebookServer
  # base path: http://localhost/v1
  # Shutdown a notebook server
  # @param namespace character namespace notebook is in (an organization name or user's username)
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateNotebookName", {
  # tests for UpdateNotebookName
  # base path: http://localhost/v1
  # update name on a notebok, moving related s3 object to new location
  # @param namespace character namespace array is in (an organization name or user's username)
  # @param array character name/uri of notebook (array) that is url-encoded
  # @param notebook.metadata ArrayInfoUpdate notebook (array) metadata to update
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

