# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DomainArray")

model.instance <- DomainArray$new()

test_that("int8", {
  # tests for the property `int8` (array[integer])

  # uncomment below to test the property 
  #expect_equal(model.instance$`int8`, "EXPECTED_RESULT")
})

test_that("uint8", {
  # tests for the property `uint8` (array[integer])

  # uncomment below to test the property 
  #expect_equal(model.instance$`uint8`, "EXPECTED_RESULT")
})

test_that("int16", {
  # tests for the property `int16` (array[integer])

  # uncomment below to test the property 
  #expect_equal(model.instance$`int16`, "EXPECTED_RESULT")
})

test_that("uint16", {
  # tests for the property `uint16` (array[integer])

  # uncomment below to test the property 
  #expect_equal(model.instance$`uint16`, "EXPECTED_RESULT")
})

test_that("int32", {
  # tests for the property `int32` (array[integer])

  # uncomment below to test the property 
  #expect_equal(model.instance$`int32`, "EXPECTED_RESULT")
})

test_that("uint32", {
  # tests for the property `uint32` (array[integer])

  # uncomment below to test the property 
  #expect_equal(model.instance$`uint32`, "EXPECTED_RESULT")
})

test_that("int64", {
  # tests for the property `int64` (array[integer])

  # uncomment below to test the property 
  #expect_equal(model.instance$`int64`, "EXPECTED_RESULT")
})

test_that("uint64", {
  # tests for the property `uint64` (array[integer])

  # uncomment below to test the property 
  #expect_equal(model.instance$`uint64`, "EXPECTED_RESULT")
})

test_that("float32", {
  # tests for the property `float32` (array[numeric])

  # uncomment below to test the property 
  #expect_equal(model.instance$`float32`, "EXPECTED_RESULT")
})

test_that("float64", {
  # tests for the property `float64` (array[numeric])

  # uncomment below to test the property 
  #expect_equal(model.instance$`float64`, "EXPECTED_RESULT")
})

