# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test StatsApi")

api.instance <- StatsApi$new()

test_that("GetTiledbStats", {
  # tests for GetTiledbStats
  # base path: http://localhost/v1
  # Fetch libtiledb stat
  # @return [InlineResponse200]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

