# TileDB Storage Platform API
#
# TileDB Storage Platform REST API
#
# The version of the OpenAPI document: 2.2.19
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ArrayFavorite
#'
#' @description ArrayFavorite Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character [optional]
#'
#' @field created_at  character [optional]
#'
#' @field array_uuid  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ArrayFavorite <- R6::R6Class(
  'ArrayFavorite',
  public = list(
    `id` = NULL,
    `created_at` = NULL,
    `array_uuid` = NULL,
    initialize = function(
        `id`=NULL, `created_at`=NULL, `array_uuid`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`created_at`)) {
        stopifnot(is.character(`created_at`), length(`created_at`) == 1)
        self$`created_at` <- `created_at`
      }
      if (!is.null(`array_uuid`)) {
        stopifnot(is.character(`array_uuid`), length(`array_uuid`) == 1)
        self$`array_uuid` <- `array_uuid`
      }
    },
    toJSON = function() {
      ArrayFavoriteObject <- list()
      if (!is.null(self$`id`)) {
        ArrayFavoriteObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`created_at`)) {
        ArrayFavoriteObject[['created_at']] <-
          self$`created_at`
      }
      if (!is.null(self$`array_uuid`)) {
        ArrayFavoriteObject[['array_uuid']] <-
          self$`array_uuid`
      }

      ArrayFavoriteObject
    },
    fromJSON = function(ArrayFavoriteJson) {
      ArrayFavoriteObject <- jsonlite::fromJSON(ArrayFavoriteJson)
      if (!is.null(ArrayFavoriteObject$`id`)) {
        self$`id` <- ArrayFavoriteObject$`id`
      }
      if (!is.null(ArrayFavoriteObject$`created_at`)) {
        self$`created_at` <- ArrayFavoriteObject$`created_at`
      }
      if (!is.null(ArrayFavoriteObject$`array_uuid`)) {
        self$`array_uuid` <- ArrayFavoriteObject$`array_uuid`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`created_at`)) {
        sprintf(
        '"created_at":
          "%s"
                ',
        self$`created_at`
        )},
        if (!is.null(self$`array_uuid`)) {
        sprintf(
        '"array_uuid":
          "%s"
                ',
        self$`array_uuid`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ArrayFavoriteJson) {
      ArrayFavoriteObject <- jsonlite::fromJSON(ArrayFavoriteJson)
      self$`id` <- ArrayFavoriteObject$`id`
      self$`created_at` <- ArrayFavoriteObject$`created_at`
      self$`array_uuid` <- ArrayFavoriteObject$`array_uuid`
      self
    }
  )
)

