# TileDB Storage Platform API
#
# TileDB Storage Platform REST API
#
# The version of the OpenAPI document: 2.2.19
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title FavoriteCreate
#'
#' @description FavoriteCreate Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field name  character 
#'
#' @field namespace  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
FavoriteCreate <- R6::R6Class(
  'FavoriteCreate',
  public = list(
    `name` = NULL,
    `namespace` = NULL,
    initialize = function(
        `name`, `namespace`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`namespace`)) {
        stopifnot(is.character(`namespace`), length(`namespace`) == 1)
        self$`namespace` <- `namespace`
      }
    },
    toJSON = function() {
      FavoriteCreateObject <- list()
      if (!is.null(self$`name`)) {
        FavoriteCreateObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`namespace`)) {
        FavoriteCreateObject[['namespace']] <-
          self$`namespace`
      }

      FavoriteCreateObject
    },
    fromJSON = function(FavoriteCreateJson) {
      FavoriteCreateObject <- jsonlite::fromJSON(FavoriteCreateJson)
      if (!is.null(FavoriteCreateObject$`name`)) {
        self$`name` <- FavoriteCreateObject$`name`
      }
      if (!is.null(FavoriteCreateObject$`namespace`)) {
        self$`namespace` <- FavoriteCreateObject$`namespace`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`namespace`)) {
        sprintf(
        '"namespace":
          "%s"
                ',
        self$`namespace`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(FavoriteCreateJson) {
      FavoriteCreateObject <- jsonlite::fromJSON(FavoriteCreateJson)
      self$`name` <- FavoriteCreateObject$`name`
      self$`namespace` <- FavoriteCreateObject$`namespace`
      self
    }
  )
)

