# TileDB Storage Platform API
#
# TileDB Storage Platform REST API
#
# The version of the OpenAPI document: 2.1.26
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title FavoriteUpdate
#'
#' @description FavoriteUpdate Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field name  character [optional]
#'
#' @field namespace  character [optional]
#'
#' @field object_type  \link{FavoriteType} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
FavoriteUpdate <- R6::R6Class(
  'FavoriteUpdate',
  public = list(
    `name` = NULL,
    `namespace` = NULL,
    `object_type` = NULL,
    initialize = function(
        `name`=NULL, `namespace`=NULL, `object_type`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`namespace`)) {
        stopifnot(is.character(`namespace`), length(`namespace`) == 1)
        self$`namespace` <- `namespace`
      }
      if (!is.null(`object_type`)) {
        stopifnot(R6::is.R6(`object_type`))
        self$`object_type` <- `object_type`
      }
    },
    toJSON = function() {
      FavoriteUpdateObject <- list()
      if (!is.null(self$`name`)) {
        FavoriteUpdateObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`namespace`)) {
        FavoriteUpdateObject[['namespace']] <-
          self$`namespace`
      }
      if (!is.null(self$`object_type`)) {
        FavoriteUpdateObject[['object_type']] <-
          self$`object_type`$toJSON()
      }

      FavoriteUpdateObject
    },
    fromJSON = function(FavoriteUpdateJson) {
      FavoriteUpdateObject <- jsonlite::fromJSON(FavoriteUpdateJson)
      if (!is.null(FavoriteUpdateObject$`name`)) {
        self$`name` <- FavoriteUpdateObject$`name`
      }
      if (!is.null(FavoriteUpdateObject$`namespace`)) {
        self$`namespace` <- FavoriteUpdateObject$`namespace`
      }
      if (!is.null(FavoriteUpdateObject$`object_type`)) {
        object_typeObject <- FavoriteType$new()
        object_typeObject$fromJSON(jsonlite::toJSON(FavoriteUpdateObject$object_type, auto_unbox = TRUE, digits = NA))
        self$`object_type` <- object_typeObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`namespace`)) {
        sprintf(
        '"namespace":
          "%s"
                ',
        self$`namespace`
        )},
        if (!is.null(self$`object_type`)) {
        sprintf(
        '"object_type":
        %s
        ',
        jsonlite::toJSON(self$`object_type`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(FavoriteUpdateJson) {
      FavoriteUpdateObject <- jsonlite::fromJSON(FavoriteUpdateJson)
      self$`name` <- FavoriteUpdateObject$`name`
      self$`namespace` <- FavoriteUpdateObject$`namespace`
      self$`object_type` <- FavoriteType$new()$fromJSON(jsonlite::toJSON(FavoriteUpdateObject$object_type, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

