# TileDB Storage Platform API
#
# TileDB Storage Platform REST API
#
# The version of the OpenAPI document: 2.2.19
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title GroupCreate
#'
#' @description GroupCreate Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field parent  character [optional]
#'
#' @field description  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GroupCreate <- R6::R6Class(
  'GroupCreate',
  public = list(
    `parent` = NULL,
    `description` = NULL,
    initialize = function(
        `parent`=NULL, `description`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`parent`)) {
        stopifnot(is.character(`parent`), length(`parent`) == 1)
        self$`parent` <- `parent`
      }
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
    },
    toJSON = function() {
      GroupCreateObject <- list()
      if (!is.null(self$`parent`)) {
        GroupCreateObject[['parent']] <-
          self$`parent`
      }
      if (!is.null(self$`description`)) {
        GroupCreateObject[['description']] <-
          self$`description`
      }

      GroupCreateObject
    },
    fromJSON = function(GroupCreateJson) {
      GroupCreateObject <- jsonlite::fromJSON(GroupCreateJson)
      if (!is.null(GroupCreateObject$`parent`)) {
        self$`parent` <- GroupCreateObject$`parent`
      }
      if (!is.null(GroupCreateObject$`description`)) {
        self$`description` <- GroupCreateObject$`description`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`parent`)) {
        sprintf(
        '"parent":
          "%s"
                ',
        self$`parent`
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(GroupCreateJson) {
      GroupCreateObject <- jsonlite::fromJSON(GroupCreateJson)
      self$`parent` <- GroupCreateObject$`parent`
      self$`description` <- GroupCreateObject$`description`
      self
    }
  )
)

