# TileDB Storage Platform API
#
# TileDB Storage Platform REST API
#
# The version of the OpenAPI document: 2.2.19
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title GroupUpdate
#'
#' @description GroupUpdate Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field name  character [optional]
#'
#' @field description  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GroupUpdate <- R6::R6Class(
  'GroupUpdate',
  public = list(
    `name` = NULL,
    `description` = NULL,
    initialize = function(
        `name`=NULL, `description`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
    },
    toJSON = function() {
      GroupUpdateObject <- list()
      if (!is.null(self$`name`)) {
        GroupUpdateObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`description`)) {
        GroupUpdateObject[['description']] <-
          self$`description`
      }

      GroupUpdateObject
    },
    fromJSON = function(GroupUpdateJson) {
      GroupUpdateObject <- jsonlite::fromJSON(GroupUpdateJson)
      if (!is.null(GroupUpdateObject$`name`)) {
        self$`name` <- GroupUpdateObject$`name`
      }
      if (!is.null(GroupUpdateObject$`description`)) {
        self$`description` <- GroupUpdateObject$`description`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(GroupUpdateJson) {
      GroupUpdateObject <- jsonlite::fromJSON(GroupUpdateJson)
      self$`name` <- GroupUpdateObject$`name`
      self$`description` <- GroupUpdateObject$`description`
      self
    }
  )
)

