# TileDB Storage Platform API
#
# TileDB Storage Platform REST API
#
# The version of the OpenAPI document: 2.2.19
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title MLModelFavorite
#'
#' @description MLModelFavorite Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character [optional]
#'
#' @field created_at  character [optional]
#'
#' @field mlmodel_uuid  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MLModelFavorite <- R6::R6Class(
  'MLModelFavorite',
  public = list(
    `id` = NULL,
    `created_at` = NULL,
    `mlmodel_uuid` = NULL,
    initialize = function(
        `id`=NULL, `created_at`=NULL, `mlmodel_uuid`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`created_at`)) {
        stopifnot(is.character(`created_at`), length(`created_at`) == 1)
        self$`created_at` <- `created_at`
      }
      if (!is.null(`mlmodel_uuid`)) {
        stopifnot(is.character(`mlmodel_uuid`), length(`mlmodel_uuid`) == 1)
        self$`mlmodel_uuid` <- `mlmodel_uuid`
      }
    },
    toJSON = function() {
      MLModelFavoriteObject <- list()
      if (!is.null(self$`id`)) {
        MLModelFavoriteObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`created_at`)) {
        MLModelFavoriteObject[['created_at']] <-
          self$`created_at`
      }
      if (!is.null(self$`mlmodel_uuid`)) {
        MLModelFavoriteObject[['mlmodel_uuid']] <-
          self$`mlmodel_uuid`
      }

      MLModelFavoriteObject
    },
    fromJSON = function(MLModelFavoriteJson) {
      MLModelFavoriteObject <- jsonlite::fromJSON(MLModelFavoriteJson)
      if (!is.null(MLModelFavoriteObject$`id`)) {
        self$`id` <- MLModelFavoriteObject$`id`
      }
      if (!is.null(MLModelFavoriteObject$`created_at`)) {
        self$`created_at` <- MLModelFavoriteObject$`created_at`
      }
      if (!is.null(MLModelFavoriteObject$`mlmodel_uuid`)) {
        self$`mlmodel_uuid` <- MLModelFavoriteObject$`mlmodel_uuid`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`created_at`)) {
        sprintf(
        '"created_at":
          "%s"
                ',
        self$`created_at`
        )},
        if (!is.null(self$`mlmodel_uuid`)) {
        sprintf(
        '"mlmodel_uuid":
          "%s"
                ',
        self$`mlmodel_uuid`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(MLModelFavoriteJson) {
      MLModelFavoriteObject <- jsonlite::fromJSON(MLModelFavoriteJson)
      self$`id` <- MLModelFavoriteObject$`id`
      self$`created_at` <- MLModelFavoriteObject$`created_at`
      self$`mlmodel_uuid` <- MLModelFavoriteObject$`mlmodel_uuid`
      self
    }
  )
)

