# TileDB Storage Platform API
#
# TileDB Storage Platform REST API
#
# The version of the OpenAPI document: 2.2.19
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title NotebookFavorite
#'
#' @description NotebookFavorite Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character [optional]
#'
#' @field created_at  character [optional]
#'
#' @field notebook_uuid  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
NotebookFavorite <- R6::R6Class(
  'NotebookFavorite',
  public = list(
    `id` = NULL,
    `created_at` = NULL,
    `notebook_uuid` = NULL,
    initialize = function(
        `id`=NULL, `created_at`=NULL, `notebook_uuid`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`created_at`)) {
        stopifnot(is.character(`created_at`), length(`created_at`) == 1)
        self$`created_at` <- `created_at`
      }
      if (!is.null(`notebook_uuid`)) {
        stopifnot(is.character(`notebook_uuid`), length(`notebook_uuid`) == 1)
        self$`notebook_uuid` <- `notebook_uuid`
      }
    },
    toJSON = function() {
      NotebookFavoriteObject <- list()
      if (!is.null(self$`id`)) {
        NotebookFavoriteObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`created_at`)) {
        NotebookFavoriteObject[['created_at']] <-
          self$`created_at`
      }
      if (!is.null(self$`notebook_uuid`)) {
        NotebookFavoriteObject[['notebook_uuid']] <-
          self$`notebook_uuid`
      }

      NotebookFavoriteObject
    },
    fromJSON = function(NotebookFavoriteJson) {
      NotebookFavoriteObject <- jsonlite::fromJSON(NotebookFavoriteJson)
      if (!is.null(NotebookFavoriteObject$`id`)) {
        self$`id` <- NotebookFavoriteObject$`id`
      }
      if (!is.null(NotebookFavoriteObject$`created_at`)) {
        self$`created_at` <- NotebookFavoriteObject$`created_at`
      }
      if (!is.null(NotebookFavoriteObject$`notebook_uuid`)) {
        self$`notebook_uuid` <- NotebookFavoriteObject$`notebook_uuid`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`created_at`)) {
        sprintf(
        '"created_at":
          "%s"
                ',
        self$`created_at`
        )},
        if (!is.null(self$`notebook_uuid`)) {
        sprintf(
        '"notebook_uuid":
          "%s"
                ',
        self$`notebook_uuid`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(NotebookFavoriteJson) {
      NotebookFavoriteObject <- jsonlite::fromJSON(NotebookFavoriteJson)
      self$`id` <- NotebookFavoriteObject$`id`
      self$`created_at` <- NotebookFavoriteObject$`created_at`
      self$`notebook_uuid` <- NotebookFavoriteObject$`notebook_uuid`
      self
    }
  )
)

