# TileDB Storage Platform API
#
# TileDB Storage Platform REST API
#
# The version of the OpenAPI document: 2.2.19
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title QueryRanges
#'
#' @description QueryRanges Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field layout  \link{Layout} [optional]
#'
#' @field ranges  list( \link{array[numeric]} ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
QueryRanges <- R6::R6Class(
  'QueryRanges',
  public = list(
    `layout` = NULL,
    `ranges` = NULL,
    initialize = function(
        `layout`=NULL, `ranges`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`layout`)) {
        stopifnot(R6::is.R6(`layout`))
        self$`layout` <- `layout`
      }
      if (!is.null(`ranges`)) {
        stopifnot(is.vector(`ranges`), length(`ranges`) != 0)
        sapply(`ranges`, function(x) stopifnot(R6::is.R6(x)))
        self$`ranges` <- `ranges`
      }
    },
    toJSON = function() {
      QueryRangesObject <- list()
      if (!is.null(self$`layout`)) {
        QueryRangesObject[['layout']] <-
          self$`layout`$toJSON()
      }
      if (!is.null(self$`ranges`)) {
        QueryRangesObject[['ranges']] <-
          lapply(self$`ranges`, function(x) x$toJSON())
      }

      QueryRangesObject
    },
    fromJSON = function(QueryRangesJson) {
      QueryRangesObject <- jsonlite::fromJSON(QueryRangesJson)
      if (!is.null(QueryRangesObject$`layout`)) {
        #layoutObject <- Layout$new()
        layoutObject <- Layout$new(QueryRangesObject$layout)
        layoutObject$fromJSON(jsonlite::toJSON(QueryRangesObject$layout, auto_unbox = TRUE, digits = NA))
        self$`layout` <- layoutObject
      }
      if (!is.null(QueryRangesObject$`ranges`)) {
        self$`ranges` <- ApiClient$new()$deserializeObj(QueryRangesObject$`ranges`, "array[array[numeric]]", loadNamespace("tiledbcloud"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`layout`)) {
        sprintf(
        '"layout":
        %s
        ',
        jsonlite::toJSON(self$`layout`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`ranges`)) {
        sprintf(
        '"ranges":
        [%s]
',
        paste(sapply(self$`ranges`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(QueryRangesJson) {
      QueryRangesObject <- jsonlite::fromJSON(QueryRangesJson)
      self$`layout` <- Layout$new()$fromJSON(jsonlite::toJSON(QueryRangesObject$layout, auto_unbox = TRUE, digits = NA))
      self$`ranges` <- ApiClient$new()$deserializeObj(QueryRangesObject$`ranges`, "array[array[numeric]]", loadNamespace("tiledbcloud"))
      self
    }
  )
)

