##' TileDB Cloud HTTP-response helper
##'
##' Used for overriding the openapi autogenerated HTTP-response handling:
##' * Makes the handling compatible with TileDB REST-server response format
##' * Surfaces error messages back to the user
##' Not intended to be exported from this package; for package-internal use only.
#
##'
##' @param resp A \code{response} S3 object e.g. from \code{httr:GET}.
##'
##' @return The R object which is decoded.
##' @export
decode_response <- function(resp) {
  # Goal: unpack the useful bits and surface them; avoid showing non-useful bits.
  # * The response object `resp` is an S3 object (list with generic functions)
  #   having named slots including `resp$status_code` and `resp$content`, along
  #   with others.
  # * `resp$content` is the "HTTP body" per se which is in raw format so we need
  #   to do `rawToChar` to see a familiar string containing human-readable JSON.
  # *
  #
  # - resp
  #   - resp$status_code
  #   - resp$content
  #     - this is raw; convert to char; now it's a JSON string like
  #       {
  #         "code": 5000,
  #         "message": "some error details go here",
  #         "request_id": "e78e0e95-a991-4a4f-b302-3b2af2d7c844"
  #       }
  #     - JSON-parse that to get an R named list with keys "code", "message", "request_id".
  #     - If there is indeed a "message" key, return that value as payload; otherwise
  #       return the full JSON string

  status_code <- httr::status_code(resp)
  body <- resp$content

  # Happy/2xx cases. Don't try to decode the content (body) object (nominally
  # also a JSON string, raw-encoded): leave that to the caller.
  if (status_code >= 200 && status_code <= 299) {
    return(ApiResponse$new(body, resp))
  }

  # Response has no HTTP body
  if (is.null(body)) {
    return(ApiResponse$new(paste("Server returned" , status_code , "response status code.")))
  }

  # Response has HTTP body; return "message" component from parsed body-JSON, else full body as string.
  bodyAsJSONString <- rawToChar(body)
  bodyAsNamedList <- jsonlite::fromJSON(bodyAsJSONString)

  if (is.null(bodyAsNamedList$message)) {
    return(ApiResponse$new(paste("Server returned" , status_code , "response status code. Content: ", bodyAsJSONString), resp))
  } else {
    return(ApiResponse$new(paste("Server returned" , status_code , "response status code. Message: ", bodyAsNamedList$message), resp))
  }
}
