# TileDB Storage Platform API
#
# TileDB Storage Platform REST API
#
# The version of the OpenAPI document: 2.2.19
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title UDFFavorite
#'
#' @description UDFFavorite Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character [optional]
#'
#' @field created_at  character [optional]
#'
#' @field udf_uuid  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
UDFFavorite <- R6::R6Class(
  'UDFFavorite',
  public = list(
    `id` = NULL,
    `created_at` = NULL,
    `udf_uuid` = NULL,
    initialize = function(
        `id`=NULL, `created_at`=NULL, `udf_uuid`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`created_at`)) {
        stopifnot(is.character(`created_at`), length(`created_at`) == 1)
        self$`created_at` <- `created_at`
      }
      if (!is.null(`udf_uuid`)) {
        stopifnot(is.character(`udf_uuid`), length(`udf_uuid`) == 1)
        self$`udf_uuid` <- `udf_uuid`
      }
    },
    toJSON = function() {
      UDFFavoriteObject <- list()
      if (!is.null(self$`id`)) {
        UDFFavoriteObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`created_at`)) {
        UDFFavoriteObject[['created_at']] <-
          self$`created_at`
      }
      if (!is.null(self$`udf_uuid`)) {
        UDFFavoriteObject[['udf_uuid']] <-
          self$`udf_uuid`
      }

      UDFFavoriteObject
    },
    fromJSON = function(UDFFavoriteJson) {
      UDFFavoriteObject <- jsonlite::fromJSON(UDFFavoriteJson)
      if (!is.null(UDFFavoriteObject$`id`)) {
        self$`id` <- UDFFavoriteObject$`id`
      }
      if (!is.null(UDFFavoriteObject$`created_at`)) {
        self$`created_at` <- UDFFavoriteObject$`created_at`
      }
      if (!is.null(UDFFavoriteObject$`udf_uuid`)) {
        self$`udf_uuid` <- UDFFavoriteObject$`udf_uuid`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`created_at`)) {
        sprintf(
        '"created_at":
          "%s"
                ',
        self$`created_at`
        )},
        if (!is.null(self$`udf_uuid`)) {
        sprintf(
        '"udf_uuid":
          "%s"
                ',
        self$`udf_uuid`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(UDFFavoriteJson) {
      UDFFavoriteObject <- jsonlite::fromJSON(UDFFavoriteJson)
      self$`id` <- UDFFavoriteObject$`id`
      self$`created_at` <- UDFFavoriteObject$`created_at`
      self$`udf_uuid` <- UDFFavoriteObject$`udf_uuid`
      self
    }
  )
)

