# Run CI for R based on copy of https://eddelbuettel.github.io/r-ci/

name: ci

on:
  push:
  # Having push & pull_request both simply makes a double/redundant CI run
  # pull_request:
  workflow_dispatch:

env:
  _R_CHECK_FORCE_SUGGESTS_: "FALSE"

  # Avoid the sad and frightfully unhelpful "Last 13 lines of output:"
  # actively prohibits our ability to debug CI failures
  _R_CHECK_TESTS_NLINES_: 0

  TILEDB_REST_HOST: "https://api.tiledb.com"
  TILEDB_REST_TOKEN_UNITTEST: ${{ secrets.TILEDB_REST_TOKEN_UNITTEST }}
  TILEDB_REST_UNIT_TEST_NAMESPACE_TO_CHARGE: "unittest"
  
jobs:
  ci:
    strategy:
      matrix:
        include:
          - {os: ubuntu-latest}
          - {os: macOS-latest}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Bootstrap
        run: ./.github/r-ci.sh bootstrap

      - name: Dependencies
        run: ./.github/r-ci.sh install_all

      - name: Test
        run: ./.github/r-ci.sh run_tests
